-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity xor_1_hw is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    state_matrix_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    state_matrix_ce0 : OUT STD_LOGIC;
    state_matrix_we0 : OUT STD_LOGIC;
    state_matrix_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    state_matrix_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    index1 : IN STD_LOGIC_VECTOR (4 downto 0);
    index2 : IN STD_LOGIC_VECTOR (5 downto 0);
    arr1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    arr1_ce0 : OUT STD_LOGIC;
    arr1_we0 : OUT STD_LOGIC;
    arr1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    arr1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    arr2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    arr2_ce0 : OUT STD_LOGIC;
    arr2_we0 : OUT STD_LOGIC;
    arr2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    arr2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    arr3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    arr3_ce0 : OUT STD_LOGIC;
    arr3_we0 : OUT STD_LOGIC;
    arr3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    arr3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    arr3_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    arr3_ce1 : OUT STD_LOGIC;
    arr3_we1 : OUT STD_LOGIC;
    arr3_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    arr3_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    arr4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    arr4_ce0 : OUT STD_LOGIC;
    arr4_we0 : OUT STD_LOGIC;
    arr4_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    arr4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    arr4_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    arr4_ce1 : OUT STD_LOGIC;
    arr4_we1 : OUT STD_LOGIC;
    arr4_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of xor_1_hw is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (12 downto 0) := "0000000100000";
    constant ap_ST_fsm_pp2_stage0 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_ST_fsm_pp3_stage0 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_ST_fsm_pp3_stage1 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (12 downto 0) := "0010000000000";
    constant ap_ST_fsm_pp4_stage0 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv8_30 : STD_LOGIC_VECTOR (7 downto 0) := "00110000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv8_31 : STD_LOGIC_VECTOR (7 downto 0) := "00110001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv7_30 : STD_LOGIC_VECTOR (6 downto 0) := "0110000";
    constant ap_const_lv7_31 : STD_LOGIC_VECTOR (6 downto 0) := "0110001";
    constant ap_const_lv7_32 : STD_LOGIC_VECTOR (6 downto 0) := "0110010";
    constant ap_const_lv7_33 : STD_LOGIC_VECTOR (6 downto 0) := "0110011";
    constant ap_const_lv7_65 : STD_LOGIC_VECTOR (6 downto 0) := "1100101";
    constant ap_const_lv7_66 : STD_LOGIC_VECTOR (6 downto 0) := "1100110";
    constant ap_const_lv7_34 : STD_LOGIC_VECTOR (6 downto 0) := "0110100";
    constant ap_const_lv7_35 : STD_LOGIC_VECTOR (6 downto 0) := "0110101";
    constant ap_const_lv7_36 : STD_LOGIC_VECTOR (6 downto 0) := "0110110";
    constant ap_const_lv7_37 : STD_LOGIC_VECTOR (6 downto 0) := "0110111";
    constant ap_const_lv7_38 : STD_LOGIC_VECTOR (6 downto 0) := "0111000";
    constant ap_const_lv7_39 : STD_LOGIC_VECTOR (6 downto 0) := "0111001";
    constant ap_const_lv7_61 : STD_LOGIC_VECTOR (6 downto 0) := "1100001";
    constant ap_const_lv7_62 : STD_LOGIC_VECTOR (6 downto 0) := "1100010";
    constant ap_const_lv7_63 : STD_LOGIC_VECTOR (6 downto 0) := "1100011";
    constant ap_const_lv7_64 : STD_LOGIC_VECTOR (6 downto 0) := "1100100";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal i_0_reg_264 : STD_LOGIC_VECTOR (3 downto 0);
    signal i1_0_reg_276 : STD_LOGIC_VECTOR (3 downto 0);
    signal i2_0_reg_288 : STD_LOGIC_VECTOR (5 downto 0);
    signal i_0_i_reg_299 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_0_i_reg_299_pp3_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_pp3_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp3_stage0 : signal is "none";
    signal ap_block_state12_pp3_stage0_iter0 : BOOLEAN;
    signal ap_block_state14_pp3_stage0_iter1 : BOOLEAN;
    signal ap_block_pp3_stage0_11001 : BOOLEAN;
    signal i3_0_reg_311 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln344_fu_370_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln344_reg_792 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln342_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln342_reg_798 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_fu_382_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_reg_802 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal add_ln349_fu_426_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln349_reg_812 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln347_fu_432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln347_reg_817 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_block_state5_pp1_stage0_iter0 : BOOLEAN;
    signal ap_block_state6_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal i_1_fu_438_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_1_reg_821 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal icmp_ln355_fu_463_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln355_reg_831 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp2_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp2_stage0 : signal is "none";
    signal ap_block_state9_pp2_stage0_iter0 : BOOLEAN;
    signal ap_block_state10_pp2_stage0_iter1 : BOOLEAN;
    signal ap_block_pp2_stage0_11001 : BOOLEAN;
    signal i_2_fu_469_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_enable_reg_pp2_iter0 : STD_LOGIC := '0';
    signal arr3_addr_reg_840 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln114_fu_496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln114_reg_851 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln114_reg_851_pp3_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal i_3_fu_502_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_3_reg_855 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp3_iter0 : STD_LOGIC := '0';
    signal shl_ln_fu_512_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln_reg_860 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_338_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln116_reg_876 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp3_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp3_stage1 : signal is "none";
    signal ap_block_state13_pp3_stage1_iter0 : BOOLEAN;
    signal ap_block_state15_pp3_stage1_iter1 : BOOLEAN;
    signal ap_block_pp3_stage1_11001 : BOOLEAN;
    signal grp_fu_344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln117_reg_884 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln118_reg_902 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp3_iter1 : STD_LOGIC := '0';
    signal icmp_ln119_reg_909 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln118_fu_598_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln118_reg_918 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln118_1_fu_610_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln118_1_reg_924 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln367_fu_757_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln367_reg_929 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp4_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp4_stage0 : signal is "none";
    signal ap_block_state17_pp4_stage0_iter0 : BOOLEAN;
    signal ap_block_state18_pp4_stage0_iter1 : BOOLEAN;
    signal ap_block_pp4_stage0_11001 : BOOLEAN;
    signal i_4_fu_763_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp4_iter0 : STD_LOGIC := '0';
    signal add_ln369_fu_778_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln369_reg_938 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_exit_iter0_state5 : STD_LOGIC;
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_convert_hex_to_binar_fu_322_ap_ready : STD_LOGIC;
    signal grp_convert_hex_to_binar_fu_322_ap_done : STD_LOGIC;
    signal grp_convert_hex_to_binar_fu_330_ap_ready : STD_LOGIC;
    signal grp_convert_hex_to_binar_fu_330_ap_done : STD_LOGIC;
    signal ap_block_state8_on_subcall_done : BOOLEAN;
    signal ap_block_pp2_stage0_subdone : BOOLEAN;
    signal ap_condition_pp2_exit_iter0_state9 : STD_LOGIC;
    signal ap_enable_reg_pp2_iter1 : STD_LOGIC := '0';
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_block_pp3_stage0_subdone : BOOLEAN;
    signal ap_condition_pp3_exit_iter0_state12 : STD_LOGIC;
    signal ap_block_pp3_stage1_subdone : BOOLEAN;
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal ap_block_pp4_stage0_subdone : BOOLEAN;
    signal ap_condition_pp4_exit_iter0_state17 : STD_LOGIC;
    signal ap_enable_reg_pp4_iter1 : STD_LOGIC := '0';
    signal grp_convert_hex_to_binar_fu_322_ap_start : STD_LOGIC;
    signal grp_convert_hex_to_binar_fu_322_ap_idle : STD_LOGIC;
    signal grp_convert_hex_to_binar_fu_322_hex_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_convert_hex_to_binar_fu_322_hex_ce0 : STD_LOGIC;
    signal grp_convert_hex_to_binar_fu_322_bin_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_convert_hex_to_binar_fu_322_bin_ce0 : STD_LOGIC;
    signal grp_convert_hex_to_binar_fu_322_bin_we0 : STD_LOGIC;
    signal grp_convert_hex_to_binar_fu_322_bin_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_convert_hex_to_binar_fu_322_bin_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_convert_hex_to_binar_fu_322_bin_ce1 : STD_LOGIC;
    signal grp_convert_hex_to_binar_fu_322_bin_we1 : STD_LOGIC;
    signal grp_convert_hex_to_binar_fu_322_bin_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_convert_hex_to_binar_fu_330_ap_start : STD_LOGIC;
    signal grp_convert_hex_to_binar_fu_330_ap_idle : STD_LOGIC;
    signal grp_convert_hex_to_binar_fu_330_hex_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_convert_hex_to_binar_fu_330_hex_ce0 : STD_LOGIC;
    signal grp_convert_hex_to_binar_fu_330_bin_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_convert_hex_to_binar_fu_330_bin_ce0 : STD_LOGIC;
    signal grp_convert_hex_to_binar_fu_330_bin_we0 : STD_LOGIC;
    signal grp_convert_hex_to_binar_fu_330_bin_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_convert_hex_to_binar_fu_330_bin_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_convert_hex_to_binar_fu_330_bin_ce1 : STD_LOGIC;
    signal grp_convert_hex_to_binar_fu_330_bin_we1 : STD_LOGIC;
    signal grp_convert_hex_to_binar_fu_330_bin_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_i_0_phi_fu_268_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_mux_i1_0_phi_fu_280_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal ap_phi_mux_i_0_i_phi_fu_303_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp3_stage0 : BOOLEAN;
    signal grp_convert_hex_to_binar_fu_322_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_convert_hex_to_binar_fu_330_ap_start_reg : STD_LOGIC := '0';
    signal zext_ln344_4_fu_397_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln344_fu_402_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln349_4_fu_453_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln349_fu_458_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln357_fu_475_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp2_stage0 : BOOLEAN;
    signal zext_ln116_fu_520_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln117_fu_531_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln118_fu_541_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp3_stage1 : BOOLEAN;
    signal zext_ln119_fu_551_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln119_1_fu_618_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln369_fu_769_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp4_stage0 : BOOLEAN;
    signal zext_ln369_2_fu_783_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln118_1_fu_752_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln357_fu_487_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln344_fu_350_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_358_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln344_2_fu_366_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln344_1_fu_354_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln344_3_fu_388_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln344_1_fu_392_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln349_fu_407_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_9_fu_414_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln349_2_fu_422_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln349_1_fu_410_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln349_3_fu_444_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln349_1_fu_448_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln357_fu_481_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln116_fu_508_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln117_fu_525_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln118_fu_536_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln119_fu_546_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal and_ln117_fu_580_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln118_fu_584_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln119_fu_556_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln155_fu_572_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal and_ln118_1_fu_604_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln123_fu_564_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln118_fu_590_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal xor_ln117_fu_658_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln117_1_fu_663_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln118_2_fu_668_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln129_fu_623_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal and_ln118_3_fu_680_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln133_fu_630_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln118_2_fu_673_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal xor_ln116_fu_693_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln117_2_fu_698_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln118_4_fu_703_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln141_fu_637_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln118_3_fu_685_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal and_ln118_5_fu_716_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln145_fu_644_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln118_4_fu_708_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln117_1_fu_729_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln117_1_fu_733_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln118_6_fu_739_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln151_fu_651_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln118_5_fu_721_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln118_6_fu_744_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln369_1_fu_774_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;
    signal ap_idle_pp2 : STD_LOGIC;
    signal ap_enable_pp2 : STD_LOGIC;
    signal ap_idle_pp3 : STD_LOGIC;
    signal ap_enable_pp3 : STD_LOGIC;
    signal ap_idle_pp4 : STD_LOGIC;
    signal ap_enable_pp4 : STD_LOGIC;

    component convert_hex_to_binar IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        hex_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hex_ce0 : OUT STD_LOGIC;
        hex_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        bin_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        bin_ce0 : OUT STD_LOGIC;
        bin_we0 : OUT STD_LOGIC;
        bin_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        bin_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        bin_ce1 : OUT STD_LOGIC;
        bin_we1 : OUT STD_LOGIC;
        bin_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    grp_convert_hex_to_binar_fu_322 : component convert_hex_to_binar
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_convert_hex_to_binar_fu_322_ap_start,
        ap_done => grp_convert_hex_to_binar_fu_322_ap_done,
        ap_idle => grp_convert_hex_to_binar_fu_322_ap_idle,
        ap_ready => grp_convert_hex_to_binar_fu_322_ap_ready,
        hex_address0 => grp_convert_hex_to_binar_fu_322_hex_address0,
        hex_ce0 => grp_convert_hex_to_binar_fu_322_hex_ce0,
        hex_q0 => arr1_q0,
        bin_address0 => grp_convert_hex_to_binar_fu_322_bin_address0,
        bin_ce0 => grp_convert_hex_to_binar_fu_322_bin_ce0,
        bin_we0 => grp_convert_hex_to_binar_fu_322_bin_we0,
        bin_d0 => grp_convert_hex_to_binar_fu_322_bin_d0,
        bin_address1 => grp_convert_hex_to_binar_fu_322_bin_address1,
        bin_ce1 => grp_convert_hex_to_binar_fu_322_bin_ce1,
        bin_we1 => grp_convert_hex_to_binar_fu_322_bin_we1,
        bin_d1 => grp_convert_hex_to_binar_fu_322_bin_d1);

    grp_convert_hex_to_binar_fu_330 : component convert_hex_to_binar
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_convert_hex_to_binar_fu_330_ap_start,
        ap_done => grp_convert_hex_to_binar_fu_330_ap_done,
        ap_idle => grp_convert_hex_to_binar_fu_330_ap_idle,
        ap_ready => grp_convert_hex_to_binar_fu_330_ap_ready,
        hex_address0 => grp_convert_hex_to_binar_fu_330_hex_address0,
        hex_ce0 => grp_convert_hex_to_binar_fu_330_hex_ce0,
        hex_q0 => arr2_q0,
        bin_address0 => grp_convert_hex_to_binar_fu_330_bin_address0,
        bin_ce0 => grp_convert_hex_to_binar_fu_330_bin_ce0,
        bin_we0 => grp_convert_hex_to_binar_fu_330_bin_we0,
        bin_d0 => grp_convert_hex_to_binar_fu_330_bin_d0,
        bin_address1 => grp_convert_hex_to_binar_fu_330_bin_address1,
        bin_ce1 => grp_convert_hex_to_binar_fu_330_bin_ce1,
        bin_we1 => grp_convert_hex_to_binar_fu_330_bin_we1,
        bin_d1 => grp_convert_hex_to_binar_fu_330_bin_d1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state5) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state5))) then 
                    ap_enable_reg_pp1_iter1 <= (ap_const_logic_1 xor ap_condition_pp1_exit_iter0_state5);
                elsif ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp2_exit_iter0_state9) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
                    ap_enable_reg_pp2_iter0 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state8_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                    ap_enable_reg_pp2_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp2_exit_iter0_state9))) then 
                    ap_enable_reg_pp2_iter1 <= (ap_const_logic_1 xor ap_condition_pp2_exit_iter0_state9);
                elsif ((ap_const_boolean_0 = ap_block_pp2_stage0_subdone)) then 
                    ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
                elsif (((ap_const_boolean_0 = ap_block_state8_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                    ap_enable_reg_pp2_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp3_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp3_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp3_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (ap_const_logic_1 = ap_condition_pp3_exit_iter0_state12))) then 
                    ap_enable_reg_pp3_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    ap_enable_reg_pp3_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp3_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp3_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp3_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage1))) then 
                    ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    ap_enable_reg_pp3_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp4_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp4_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp4_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp4_exit_iter0_state17) and (ap_const_logic_1 = ap_CS_fsm_pp4_stage0))) then 
                    ap_enable_reg_pp4_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                    ap_enable_reg_pp4_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp4_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp4_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp4_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp4_exit_iter0_state17))) then 
                    ap_enable_reg_pp4_iter1 <= (ap_const_logic_1 xor ap_condition_pp4_exit_iter0_state17);
                elsif ((ap_const_boolean_0 = ap_block_pp4_stage0_subdone)) then 
                    ap_enable_reg_pp4_iter1 <= ap_enable_reg_pp4_iter0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                    ap_enable_reg_pp4_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_convert_hex_to_binar_fu_322_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_convert_hex_to_binar_fu_322_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_convert_hex_to_binar_fu_322_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_convert_hex_to_binar_fu_322_ap_ready = ap_const_logic_1)) then 
                    grp_convert_hex_to_binar_fu_322_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_convert_hex_to_binar_fu_330_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_convert_hex_to_binar_fu_330_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_convert_hex_to_binar_fu_330_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_convert_hex_to_binar_fu_330_ap_ready = ap_const_logic_1)) then 
                    grp_convert_hex_to_binar_fu_330_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i1_0_reg_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                i1_0_reg_276 <= ap_const_lv4_0;
            elsif (((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln347_reg_817 = ap_const_lv1_0))) then 
                i1_0_reg_276 <= i_1_reg_821;
            end if; 
        end if;
    end process;

    i2_0_reg_288_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (icmp_ln355_fu_463_p2 = ap_const_lv1_0))) then 
                i2_0_reg_288 <= i_2_fu_469_p2;
            elsif (((ap_const_boolean_0 = ap_block_state8_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                i2_0_reg_288 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    i3_0_reg_311_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                i3_0_reg_311 <= ap_const_lv4_0;
            elsif (((ap_const_boolean_0 = ap_block_pp4_stage0_11001) and (ap_enable_reg_pp4_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp4_stage0) and (icmp_ln367_fu_757_p2 = ap_const_lv1_0))) then 
                i3_0_reg_311 <= i_4_fu_763_p2;
            end if; 
        end if;
    end process;

    i_0_i_reg_299_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                i_0_i_reg_299 <= ap_const_lv4_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (icmp_ln114_reg_851 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001))) then 
                i_0_i_reg_299 <= i_3_reg_855;
            end if; 
        end if;
    end process;

    i_0_reg_264_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln342_reg_798 = ap_const_lv1_0))) then 
                i_0_reg_264 <= i_reg_802;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_0_reg_264 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                add_ln344_reg_792 <= add_ln344_fu_370_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln349_reg_812 <= add_ln349_fu_426_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp4_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp4_stage0) and (icmp_ln367_fu_757_p2 = ap_const_lv1_0))) then
                add_ln369_reg_938 <= add_ln369_fu_778_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (icmp_ln355_fu_463_p2 = ap_const_lv1_0))) then
                arr3_addr_reg_840 <= zext_ln357_fu_475_p1(5 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001))) then
                i_0_i_reg_299_pp3_iter1_reg <= i_0_i_reg_299;
                icmp_ln114_reg_851 <= icmp_ln114_fu_496_p2;
                icmp_ln114_reg_851_pp3_iter1_reg <= icmp_ln114_reg_851;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                i_1_reg_821 <= i_1_fu_438_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001))) then
                i_3_reg_855 <= i_3_fu_502_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                i_reg_802 <= i_fu_382_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage1) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (icmp_ln114_reg_851 = ap_const_lv1_0))) then
                icmp_ln116_reg_876 <= grp_fu_338_p2;
                icmp_ln117_reg_884 <= grp_fu_344_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (icmp_ln114_reg_851 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001))) then
                icmp_ln118_reg_902 <= grp_fu_338_p2;
                icmp_ln119_reg_909 <= grp_fu_344_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln342_reg_798 <= icmp_ln342_fu_376_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                icmp_ln347_reg_817 <= icmp_ln347_fu_432_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (ap_const_boolean_0 = ap_block_pp2_stage0_11001))) then
                icmp_ln355_reg_831 <= icmp_ln355_fu_463_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp4_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp4_stage0))) then
                icmp_ln367_reg_929 <= icmp_ln367_fu_757_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (icmp_ln114_reg_851 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001))) then
                    select_ln118_1_reg_924(2 downto 0) <= select_ln118_1_fu_610_p3(2 downto 0);    select_ln118_1_reg_924(4) <= select_ln118_1_fu_610_p3(4);    select_ln118_1_reg_924(6) <= select_ln118_1_fu_610_p3(6);
                xor_ln118_reg_918 <= xor_ln118_fu_598_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (icmp_ln114_fu_496_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001))) then
                    shl_ln_reg_860(4 downto 2) <= shl_ln_fu_512_p3(4 downto 2);
            end if;
        end if;
    end process;
    shl_ln_reg_860(1 downto 0) <= "00";
    select_ln118_1_reg_924(3) <= '0';
    select_ln118_1_reg_924(5) <= '1';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln342_fu_376_p2, ap_enable_reg_pp0_iter0, icmp_ln347_fu_432_p2, ap_enable_reg_pp1_iter0, icmp_ln355_fu_463_p2, ap_enable_reg_pp2_iter0, icmp_ln114_fu_496_p2, ap_enable_reg_pp3_iter0, ap_CS_fsm_pp3_stage1, ap_enable_reg_pp3_iter1, icmp_ln367_fu_757_p2, ap_enable_reg_pp4_iter0, ap_block_pp0_stage0_subdone, ap_block_pp1_stage0_subdone, ap_CS_fsm_state8, ap_block_state8_on_subcall_done, ap_block_pp2_stage0_subdone, ap_block_pp3_stage0_subdone, ap_block_pp3_stage1_subdone, ap_block_pp4_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln342_fu_376_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln342_fu_376_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
            when ap_ST_fsm_pp1_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (icmp_ln347_fu_432_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (icmp_ln347_fu_432_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_boolean_0 = ap_block_state8_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_pp2_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_pp2_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (icmp_ln355_fu_463_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp2_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp2_stage0_subdone) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (icmp_ln355_fu_463_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp2_stage0;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_pp3_stage0;
            when ap_ST_fsm_pp3_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp3_stage0_subdone) and (ap_enable_reg_pp3_iter1 = ap_const_logic_0) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (icmp_ln114_fu_496_p2 = ap_const_lv1_1))) and (ap_const_boolean_0 = ap_block_pp3_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp3_stage1;
                elsif (((ap_const_boolean_0 = ap_block_pp3_stage0_subdone) and (ap_enable_reg_pp3_iter1 = ap_const_logic_0) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (icmp_ln114_fu_496_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp3_stage0;
                end if;
            when ap_ST_fsm_pp3_stage1 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp3_stage1_subdone) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage1) and (ap_enable_reg_pp3_iter0 = ap_const_logic_0))) and (ap_const_boolean_0 = ap_block_pp3_stage1_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp3_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp3_stage1_subdone) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage1) and (ap_enable_reg_pp3_iter0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp3_stage1;
                end if;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_pp4_stage0;
            when ap_ST_fsm_pp4_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp4_stage0_subdone) and (icmp_ln367_fu_757_p2 = ap_const_lv1_1) and (ap_enable_reg_pp4_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp4_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp4_stage0_subdone) and (icmp_ln367_fu_757_p2 = ap_const_lv1_1) and (ap_enable_reg_pp4_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state19;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp4_stage0;
                end if;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXX";
        end case;
    end process;
    add_ln344_1_fu_392_p2 <= std_logic_vector(unsigned(add_ln344_reg_792) + unsigned(zext_ln344_3_fu_388_p1));
    add_ln344_fu_370_p2 <= std_logic_vector(unsigned(zext_ln344_2_fu_366_p1) + unsigned(zext_ln344_1_fu_354_p1));
    add_ln349_1_fu_448_p2 <= std_logic_vector(unsigned(add_ln349_reg_812) + unsigned(zext_ln349_3_fu_444_p1));
    add_ln349_fu_426_p2 <= std_logic_vector(unsigned(zext_ln349_2_fu_422_p1) + unsigned(zext_ln349_1_fu_410_p1));
    add_ln369_fu_778_p2 <= std_logic_vector(unsigned(add_ln344_reg_792) + unsigned(zext_ln369_1_fu_774_p1));
    and_ln117_1_fu_663_p2 <= (xor_ln117_fu_658_p2 and icmp_ln116_reg_876);
    and_ln117_2_fu_698_p2 <= (xor_ln116_fu_693_p2 and icmp_ln117_reg_884);
    and_ln117_fu_580_p2 <= (icmp_ln117_reg_884 and icmp_ln116_reg_876);
    and_ln118_1_fu_604_p2 <= (xor_ln118_fu_598_p2 and and_ln117_fu_580_p2);
    and_ln118_2_fu_668_p2 <= (icmp_ln118_reg_902 and and_ln117_1_fu_663_p2);
    and_ln118_3_fu_680_p2 <= (xor_ln118_reg_918 and and_ln117_1_fu_663_p2);
    and_ln118_4_fu_703_p2 <= (icmp_ln118_reg_902 and and_ln117_2_fu_698_p2);
    and_ln118_5_fu_716_p2 <= (xor_ln118_reg_918 and and_ln117_2_fu_698_p2);
    and_ln118_6_fu_739_p2 <= (xor_ln117_1_fu_733_p2 and icmp_ln118_reg_902);
    and_ln118_fu_584_p2 <= (grp_fu_338_p2 and and_ln117_fu_580_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(3);
    ap_CS_fsm_pp2_stage0 <= ap_CS_fsm(6);
    ap_CS_fsm_pp3_stage0 <= ap_CS_fsm(8);
    ap_CS_fsm_pp3_stage1 <= ap_CS_fsm(9);
    ap_CS_fsm_pp4_stage0 <= ap_CS_fsm(11);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(7);
    ap_CS_fsm_state16 <= ap_CS_fsm(10);
    ap_CS_fsm_state19 <= ap_CS_fsm(12);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);
    ap_CS_fsm_state7 <= ap_CS_fsm(4);
    ap_CS_fsm_state8 <= ap_CS_fsm(5);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp2_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp2_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp2_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp3_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp3_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp3_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp3_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp3_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp3_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp4_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp4_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp4_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp2_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp3_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp3_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp3_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp3_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp4_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp4_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp1_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp1_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_on_subcall_done_assign_proc : process(grp_convert_hex_to_binar_fu_322_ap_done, grp_convert_hex_to_binar_fu_330_ap_done)
    begin
                ap_block_state8_on_subcall_done <= ((grp_convert_hex_to_binar_fu_330_ap_done = ap_const_logic_0) or (grp_convert_hex_to_binar_fu_322_ap_done = ap_const_logic_0));
    end process;

        ap_block_state9_pp2_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln342_fu_376_p2)
    begin
        if ((icmp_ln342_fu_376_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp1_exit_iter0_state5_assign_proc : process(icmp_ln347_fu_432_p2)
    begin
        if ((icmp_ln347_fu_432_p2 = ap_const_lv1_1)) then 
            ap_condition_pp1_exit_iter0_state5 <= ap_const_logic_1;
        else 
            ap_condition_pp1_exit_iter0_state5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp2_exit_iter0_state9_assign_proc : process(icmp_ln355_fu_463_p2)
    begin
        if ((icmp_ln355_fu_463_p2 = ap_const_lv1_1)) then 
            ap_condition_pp2_exit_iter0_state9 <= ap_const_logic_1;
        else 
            ap_condition_pp2_exit_iter0_state9 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp3_exit_iter0_state12_assign_proc : process(icmp_ln114_fu_496_p2)
    begin
        if ((icmp_ln114_fu_496_p2 = ap_const_lv1_1)) then 
            ap_condition_pp3_exit_iter0_state12 <= ap_const_logic_1;
        else 
            ap_condition_pp3_exit_iter0_state12 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp4_exit_iter0_state17_assign_proc : process(icmp_ln367_fu_757_p2)
    begin
        if ((icmp_ln367_fu_757_p2 = ap_const_lv1_1)) then 
            ap_condition_pp4_exit_iter0_state17 <= ap_const_logic_1;
        else 
            ap_condition_pp4_exit_iter0_state17 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state19)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state19) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);
    ap_enable_pp2 <= (ap_idle_pp2 xor ap_const_logic_1);
    ap_enable_pp3 <= (ap_idle_pp3 xor ap_const_logic_1);
    ap_enable_pp4 <= (ap_idle_pp4 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter0, ap_enable_reg_pp1_iter1)
    begin
        if (((ap_enable_reg_pp1_iter1 = ap_const_logic_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp2_assign_proc : process(ap_enable_reg_pp2_iter0, ap_enable_reg_pp2_iter1)
    begin
        if (((ap_enable_reg_pp2_iter1 = ap_const_logic_0) and (ap_enable_reg_pp2_iter0 = ap_const_logic_0))) then 
            ap_idle_pp2 <= ap_const_logic_1;
        else 
            ap_idle_pp2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp3_assign_proc : process(ap_enable_reg_pp3_iter0, ap_enable_reg_pp3_iter1)
    begin
        if (((ap_enable_reg_pp3_iter1 = ap_const_logic_0) and (ap_enable_reg_pp3_iter0 = ap_const_logic_0))) then 
            ap_idle_pp3 <= ap_const_logic_1;
        else 
            ap_idle_pp3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp4_assign_proc : process(ap_enable_reg_pp4_iter0, ap_enable_reg_pp4_iter1)
    begin
        if (((ap_enable_reg_pp4_iter1 = ap_const_logic_0) and (ap_enable_reg_pp4_iter0 = ap_const_logic_0))) then 
            ap_idle_pp4 <= ap_const_logic_1;
        else 
            ap_idle_pp4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_i1_0_phi_fu_280_p4_assign_proc : process(i1_0_reg_276, icmp_ln347_reg_817, ap_CS_fsm_pp1_stage0, i_1_reg_821, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (icmp_ln347_reg_817 = ap_const_lv1_0))) then 
            ap_phi_mux_i1_0_phi_fu_280_p4 <= i_1_reg_821;
        else 
            ap_phi_mux_i1_0_phi_fu_280_p4 <= i1_0_reg_276;
        end if; 
    end process;


    ap_phi_mux_i_0_i_phi_fu_303_p4_assign_proc : process(i_0_i_reg_299, ap_CS_fsm_pp3_stage0, icmp_ln114_reg_851, i_3_reg_855, ap_enable_reg_pp3_iter1, ap_block_pp3_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (icmp_ln114_reg_851 = ap_const_lv1_0))) then 
            ap_phi_mux_i_0_i_phi_fu_303_p4 <= i_3_reg_855;
        else 
            ap_phi_mux_i_0_i_phi_fu_303_p4 <= i_0_i_reg_299;
        end if; 
    end process;


    ap_phi_mux_i_0_phi_fu_268_p4_assign_proc : process(i_0_reg_264, icmp_ln342_reg_798, ap_CS_fsm_pp0_stage0, i_reg_802, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln342_reg_798 = ap_const_lv1_0))) then 
            ap_phi_mux_i_0_phi_fu_268_p4 <= i_reg_802;
        else 
            ap_phi_mux_i_0_phi_fu_268_p4 <= i_0_reg_264;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    arr1_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp3_stage1, ap_enable_reg_pp3_iter1, ap_CS_fsm_pp4_stage0, ap_enable_reg_pp4_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_state8, grp_convert_hex_to_binar_fu_322_hex_address0, ap_block_pp0_stage0, zext_ln344_fu_402_p1, ap_block_pp3_stage1, zext_ln119_1_fu_618_p1, zext_ln369_fu_769_p1, ap_block_pp4_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp4_stage0) and (ap_enable_reg_pp4_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp4_stage0))) then 
            arr1_address0 <= zext_ln369_fu_769_p1(3 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp3_stage1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage1))) then 
            arr1_address0 <= zext_ln119_1_fu_618_p1(3 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            arr1_address0 <= zext_ln344_fu_402_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr1_address0 <= grp_convert_hex_to_binar_fu_322_hex_address0;
        else 
            arr1_address0 <= "XXX";
        end if; 
    end process;


    arr1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_CS_fsm_pp3_stage1, ap_block_pp3_stage1_11001, ap_enable_reg_pp3_iter1, ap_CS_fsm_pp4_stage0, ap_block_pp4_stage0_11001, ap_enable_reg_pp4_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_state8, grp_convert_hex_to_binar_fu_322_hex_ce0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp4_stage0_11001) and (ap_enable_reg_pp4_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp4_stage0)) or ((ap_const_boolean_0 = ap_block_pp3_stage1_11001) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            arr1_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr1_ce0 <= grp_convert_hex_to_binar_fu_322_hex_ce0;
        else 
            arr1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    arr1_d0_assign_proc : process(state_matrix_q0, ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp3_stage1, ap_enable_reg_pp3_iter1, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, ap_block_pp3_stage1, zext_ln118_1_fu_752_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp3_stage1) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage1))) then 
            arr1_d0 <= zext_ln118_1_fu_752_p1;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            arr1_d0 <= state_matrix_q0;
        else 
            arr1_d0 <= "XXXXXXXX";
        end if; 
    end process;


    arr1_we0_assign_proc : process(icmp_ln342_reg_798, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln114_reg_851_pp3_iter1_reg, ap_CS_fsm_pp3_stage1, ap_block_pp3_stage1_11001, ap_enable_reg_pp3_iter1, ap_enable_reg_pp0_iter1)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp3_stage1_11001) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage1) and (icmp_ln114_reg_851_pp3_iter1_reg = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln342_reg_798 = ap_const_lv1_0)))) then 
            arr1_we0 <= ap_const_logic_1;
        else 
            arr1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arr2_address0_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_CS_fsm_state8, grp_convert_hex_to_binar_fu_330_hex_address0, ap_block_pp1_stage0, zext_ln349_fu_458_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            arr2_address0 <= zext_ln349_fu_458_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr2_address0 <= grp_convert_hex_to_binar_fu_330_hex_address0;
        else 
            arr2_address0 <= "XXX";
        end if; 
    end process;


    arr2_ce0_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter1, ap_CS_fsm_state8, grp_convert_hex_to_binar_fu_330_hex_ce0)
    begin
        if (((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then 
            arr2_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr2_ce0 <= grp_convert_hex_to_binar_fu_330_hex_ce0;
        else 
            arr2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    arr2_d0 <= state_matrix_q0;

    arr2_we0_assign_proc : process(icmp_ln347_reg_817, ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter1)
    begin
        if (((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln347_reg_817 = ap_const_lv1_0))) then 
            arr2_we0 <= ap_const_logic_1;
        else 
            arr2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arr3_address0_assign_proc : process(ap_CS_fsm_pp3_stage0, ap_CS_fsm_pp2_stage0, ap_enable_reg_pp2_iter0, ap_enable_reg_pp3_iter0, ap_CS_fsm_pp3_stage1, ap_CS_fsm_state8, grp_convert_hex_to_binar_fu_322_bin_address0, ap_block_pp3_stage0, zext_ln357_fu_475_p1, ap_block_pp2_stage0, zext_ln116_fu_520_p1, zext_ln118_fu_541_p1, ap_block_pp3_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp3_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage1) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1))) then 
            arr3_address0 <= zext_ln118_fu_541_p1(5 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1))) then 
            arr3_address0 <= zext_ln116_fu_520_p1(5 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp2_stage0) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
            arr3_address0 <= zext_ln357_fu_475_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr3_address0 <= grp_convert_hex_to_binar_fu_322_bin_address0;
        else 
            arr3_address0 <= "XXXXX";
        end if; 
    end process;


    arr3_address1_assign_proc : process(ap_CS_fsm_pp3_stage0, ap_CS_fsm_pp2_stage0, arr3_addr_reg_840, ap_enable_reg_pp3_iter0, ap_CS_fsm_pp3_stage1, ap_CS_fsm_state8, ap_enable_reg_pp2_iter1, grp_convert_hex_to_binar_fu_322_bin_address1, ap_block_pp3_stage0, ap_block_pp2_stage0, zext_ln117_fu_531_p1, ap_block_pp3_stage1, zext_ln119_fu_551_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp3_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage1) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1))) then 
            arr3_address1 <= zext_ln119_fu_551_p1(5 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1))) then 
            arr3_address1 <= zext_ln117_fu_531_p1(5 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp2_stage0) and (ap_enable_reg_pp2_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
            arr3_address1 <= arr3_addr_reg_840;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr3_address1 <= grp_convert_hex_to_binar_fu_322_bin_address1;
        else 
            arr3_address1 <= "XXXXX";
        end if; 
    end process;


    arr3_ce0_assign_proc : process(ap_CS_fsm_pp3_stage0, ap_block_pp3_stage0_11001, ap_CS_fsm_pp2_stage0, ap_block_pp2_stage0_11001, ap_enable_reg_pp2_iter0, ap_enable_reg_pp3_iter0, ap_CS_fsm_pp3_stage1, ap_block_pp3_stage1_11001, ap_CS_fsm_state8, grp_convert_hex_to_binar_fu_322_bin_ce0)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001)) or ((ap_const_boolean_0 = ap_block_pp3_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage1) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1)) or ((ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (ap_const_boolean_0 = ap_block_pp2_stage0_11001)))) then 
            arr3_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr3_ce0 <= grp_convert_hex_to_binar_fu_322_bin_ce0;
        else 
            arr3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    arr3_ce1_assign_proc : process(ap_CS_fsm_pp3_stage0, ap_block_pp3_stage0_11001, ap_CS_fsm_pp2_stage0, ap_block_pp2_stage0_11001, ap_enable_reg_pp3_iter0, ap_CS_fsm_pp3_stage1, ap_block_pp3_stage1_11001, ap_CS_fsm_state8, ap_enable_reg_pp2_iter1, grp_convert_hex_to_binar_fu_322_bin_ce1)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001)) or ((ap_const_boolean_0 = ap_block_pp3_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage1) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1)) or ((ap_enable_reg_pp2_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (ap_const_boolean_0 = ap_block_pp2_stage0_11001)))) then 
            arr3_ce1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr3_ce1 <= grp_convert_hex_to_binar_fu_322_bin_ce1;
        else 
            arr3_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    arr3_d0 <= grp_convert_hex_to_binar_fu_322_bin_d0;

    arr3_d1_assign_proc : process(ap_CS_fsm_pp2_stage0, ap_CS_fsm_state8, ap_enable_reg_pp2_iter1, grp_convert_hex_to_binar_fu_322_bin_d1, ap_block_pp2_stage0, select_ln357_fu_487_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp2_stage0) and (ap_enable_reg_pp2_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
            arr3_d1 <= select_ln357_fu_487_p3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr3_d1 <= grp_convert_hex_to_binar_fu_322_bin_d1;
        else 
            arr3_d1 <= "XXXXXXXX";
        end if; 
    end process;


    arr3_we0_assign_proc : process(ap_CS_fsm_state8, grp_convert_hex_to_binar_fu_322_bin_we0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr3_we0 <= grp_convert_hex_to_binar_fu_322_bin_we0;
        else 
            arr3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arr3_we1_assign_proc : process(icmp_ln355_reg_831, ap_CS_fsm_pp2_stage0, ap_block_pp2_stage0_11001, ap_CS_fsm_state8, ap_enable_reg_pp2_iter1, grp_convert_hex_to_binar_fu_322_bin_we1)
    begin
        if (((ap_enable_reg_pp2_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (ap_const_boolean_0 = ap_block_pp2_stage0_11001) and (icmp_ln355_reg_831 = ap_const_lv1_0))) then 
            arr3_we1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr3_we1 <= grp_convert_hex_to_binar_fu_322_bin_we1;
        else 
            arr3_we1 <= ap_const_logic_0;
        end if; 
    end process;


    arr4_address0_assign_proc : process(ap_CS_fsm_pp2_stage0, ap_enable_reg_pp2_iter0, ap_CS_fsm_state8, grp_convert_hex_to_binar_fu_330_bin_address0, zext_ln357_fu_475_p1, ap_block_pp2_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp2_stage0) and (ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
            arr4_address0 <= zext_ln357_fu_475_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr4_address0 <= grp_convert_hex_to_binar_fu_330_bin_address0;
        else 
            arr4_address0 <= "XXXXX";
        end if; 
    end process;

    arr4_address1 <= grp_convert_hex_to_binar_fu_330_bin_address1;

    arr4_ce0_assign_proc : process(ap_CS_fsm_pp2_stage0, ap_block_pp2_stage0_11001, ap_enable_reg_pp2_iter0, ap_CS_fsm_state8, grp_convert_hex_to_binar_fu_330_bin_ce0)
    begin
        if (((ap_enable_reg_pp2_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0) and (ap_const_boolean_0 = ap_block_pp2_stage0_11001))) then 
            arr4_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr4_ce0 <= grp_convert_hex_to_binar_fu_330_bin_ce0;
        else 
            arr4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    arr4_ce1_assign_proc : process(ap_CS_fsm_state8, grp_convert_hex_to_binar_fu_330_bin_ce1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr4_ce1 <= grp_convert_hex_to_binar_fu_330_bin_ce1;
        else 
            arr4_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    arr4_d0 <= grp_convert_hex_to_binar_fu_330_bin_d0;
    arr4_d1 <= grp_convert_hex_to_binar_fu_330_bin_d1;

    arr4_we0_assign_proc : process(ap_CS_fsm_state8, grp_convert_hex_to_binar_fu_330_bin_we0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr4_we0 <= grp_convert_hex_to_binar_fu_330_bin_we0;
        else 
            arr4_we0 <= ap_const_logic_0;
        end if; 
    end process;


    arr4_we1_assign_proc : process(ap_CS_fsm_state8, grp_convert_hex_to_binar_fu_330_bin_we1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            arr4_we1 <= grp_convert_hex_to_binar_fu_330_bin_we1;
        else 
            arr4_we1 <= ap_const_logic_0;
        end if; 
    end process;

    grp_convert_hex_to_binar_fu_322_ap_start <= grp_convert_hex_to_binar_fu_322_ap_start_reg;
    grp_convert_hex_to_binar_fu_330_ap_start <= grp_convert_hex_to_binar_fu_330_ap_start_reg;
    grp_fu_338_p2 <= "1" when (arr3_q0 = ap_const_lv8_30) else "0";
    grp_fu_344_p2 <= "1" when (arr3_q1 = ap_const_lv8_30) else "0";
    i_1_fu_438_p2 <= std_logic_vector(unsigned(ap_phi_mux_i1_0_phi_fu_280_p4) + unsigned(ap_const_lv4_1));
    i_2_fu_469_p2 <= std_logic_vector(unsigned(i2_0_reg_288) + unsigned(ap_const_lv6_1));
    i_3_fu_502_p2 <= std_logic_vector(unsigned(ap_phi_mux_i_0_i_phi_fu_303_p4) + unsigned(ap_const_lv4_1));
    i_4_fu_763_p2 <= std_logic_vector(unsigned(i3_0_reg_311) + unsigned(ap_const_lv4_1));
    i_fu_382_p2 <= std_logic_vector(unsigned(ap_phi_mux_i_0_phi_fu_268_p4) + unsigned(ap_const_lv4_1));
    icmp_ln114_fu_496_p2 <= "1" when (ap_phi_mux_i_0_i_phi_fu_303_p4 = ap_const_lv4_8) else "0";
    icmp_ln342_fu_376_p2 <= "1" when (ap_phi_mux_i_0_phi_fu_268_p4 = ap_const_lv4_8) else "0";
    icmp_ln347_fu_432_p2 <= "1" when (ap_phi_mux_i1_0_phi_fu_280_p4 = ap_const_lv4_8) else "0";
    icmp_ln355_fu_463_p2 <= "1" when (i2_0_reg_288 = ap_const_lv6_20) else "0";
    icmp_ln357_fu_481_p2 <= "1" when (arr3_q0 = arr4_q0) else "0";
    icmp_ln367_fu_757_p2 <= "1" when (i3_0_reg_311 = ap_const_lv4_8) else "0";
    or_ln117_1_fu_729_p2 <= (icmp_ln117_reg_884 or icmp_ln116_reg_876);
    or_ln117_fu_525_p2 <= (shl_ln_fu_512_p3 or ap_const_lv5_1);
    or_ln118_fu_536_p2 <= (shl_ln_reg_860 or ap_const_lv5_2);
    or_ln119_fu_546_p2 <= (shl_ln_reg_860 or ap_const_lv5_3);
    select_ln118_1_fu_610_p3 <= 
        select_ln123_fu_564_p3 when (and_ln118_1_fu_604_p2(0) = '1') else 
        select_ln118_fu_590_p3;
    select_ln118_2_fu_673_p3 <= 
        select_ln129_fu_623_p3 when (and_ln118_2_fu_668_p2(0) = '1') else 
        select_ln118_1_reg_924;
    select_ln118_3_fu_685_p3 <= 
        select_ln133_fu_630_p3 when (and_ln118_3_fu_680_p2(0) = '1') else 
        select_ln118_2_fu_673_p3;
    select_ln118_4_fu_708_p3 <= 
        select_ln141_fu_637_p3 when (and_ln118_4_fu_703_p2(0) = '1') else 
        select_ln118_3_fu_685_p3;
    select_ln118_5_fu_721_p3 <= 
        select_ln145_fu_644_p3 when (and_ln118_5_fu_716_p2(0) = '1') else 
        select_ln118_4_fu_708_p3;
    select_ln118_6_fu_744_p3 <= 
        select_ln151_fu_651_p3 when (and_ln118_6_fu_739_p2(0) = '1') else 
        select_ln118_5_fu_721_p3;
    select_ln118_fu_590_p3 <= 
        select_ln119_fu_556_p3 when (and_ln118_fu_584_p2(0) = '1') else 
        select_ln155_fu_572_p3;
    select_ln119_fu_556_p3 <= 
        ap_const_lv7_30 when (grp_fu_344_p2(0) = '1') else 
        ap_const_lv7_31;
    select_ln123_fu_564_p3 <= 
        ap_const_lv7_32 when (grp_fu_344_p2(0) = '1') else 
        ap_const_lv7_33;
    select_ln129_fu_623_p3 <= 
        ap_const_lv7_34 when (icmp_ln119_reg_909(0) = '1') else 
        ap_const_lv7_35;
    select_ln133_fu_630_p3 <= 
        ap_const_lv7_36 when (icmp_ln119_reg_909(0) = '1') else 
        ap_const_lv7_37;
    select_ln141_fu_637_p3 <= 
        ap_const_lv7_38 when (icmp_ln119_reg_909(0) = '1') else 
        ap_const_lv7_39;
    select_ln145_fu_644_p3 <= 
        ap_const_lv7_61 when (icmp_ln119_reg_909(0) = '1') else 
        ap_const_lv7_62;
    select_ln151_fu_651_p3 <= 
        ap_const_lv7_63 when (icmp_ln119_reg_909(0) = '1') else 
        ap_const_lv7_64;
    select_ln155_fu_572_p3 <= 
        ap_const_lv7_65 when (grp_fu_344_p2(0) = '1') else 
        ap_const_lv7_66;
    select_ln357_fu_487_p3 <= 
        ap_const_lv8_30 when (icmp_ln357_fu_481_p2(0) = '1') else 
        ap_const_lv8_31;
    shl_ln_fu_512_p3 <= (trunc_ln116_fu_508_p1 & ap_const_lv2_0);

    state_matrix_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter0, ap_CS_fsm_pp4_stage0, ap_enable_reg_pp4_iter1, ap_block_pp0_stage0, ap_block_pp1_stage0, zext_ln344_4_fu_397_p1, zext_ln349_4_fu_453_p1, ap_block_pp4_stage0, zext_ln369_2_fu_783_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp4_stage0) and (ap_enable_reg_pp4_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp4_stage0))) then 
            state_matrix_address0 <= zext_ln369_2_fu_783_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            state_matrix_address0 <= zext_ln349_4_fu_453_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            state_matrix_address0 <= zext_ln344_4_fu_397_p1(8 - 1 downto 0);
        else 
            state_matrix_address0 <= "XXXXXXXX";
        end if; 
    end process;


    state_matrix_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter0, ap_CS_fsm_pp4_stage0, ap_block_pp4_stage0_11001, ap_enable_reg_pp4_iter1)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp4_stage0_11001) and (ap_enable_reg_pp4_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp4_stage0)) or ((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            state_matrix_ce0 <= ap_const_logic_1;
        else 
            state_matrix_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    state_matrix_d0 <= arr1_q0;

    state_matrix_we0_assign_proc : process(icmp_ln367_reg_929, ap_CS_fsm_pp4_stage0, ap_block_pp4_stage0_11001, ap_enable_reg_pp4_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp4_stage0_11001) and (ap_enable_reg_pp4_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp4_stage0) and (icmp_ln367_reg_929 = ap_const_lv1_0))) then 
            state_matrix_we0 <= ap_const_logic_1;
        else 
            state_matrix_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_6_fu_358_p3 <= (trunc_ln344_fu_350_p1 & ap_const_lv3_0);
    tmp_9_fu_414_p3 <= (trunc_ln349_fu_407_p1 & ap_const_lv3_0);
    trunc_ln116_fu_508_p1 <= ap_phi_mux_i_0_i_phi_fu_303_p4(3 - 1 downto 0);
    trunc_ln344_fu_350_p1 <= index1(4 - 1 downto 0);
    trunc_ln349_fu_407_p1 <= index2(4 - 1 downto 0);
    xor_ln116_fu_693_p2 <= (icmp_ln116_reg_876 xor ap_const_lv1_1);
    xor_ln117_1_fu_733_p2 <= (or_ln117_1_fu_729_p2 xor ap_const_lv1_1);
    xor_ln117_fu_658_p2 <= (icmp_ln117_reg_884 xor ap_const_lv1_1);
    xor_ln118_fu_598_p2 <= (grp_fu_338_p2 xor ap_const_lv1_1);
    zext_ln116_fu_520_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_512_p3),64));
    zext_ln117_fu_531_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln117_fu_525_p2),64));
    zext_ln118_1_fu_752_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln118_6_fu_744_p3),8));
    zext_ln118_fu_541_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln118_fu_536_p2),64));
    zext_ln119_1_fu_618_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_i_reg_299_pp3_iter1_reg),64));
    zext_ln119_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln119_fu_546_p2),64));
    zext_ln344_1_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln344_fu_350_p1),8));
    zext_ln344_2_fu_366_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_358_p3),8));
    zext_ln344_3_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_i_0_phi_fu_268_p4),8));
    zext_ln344_4_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln344_1_fu_392_p2),64));
    zext_ln344_fu_402_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_reg_264),64));
    zext_ln349_1_fu_410_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln349_fu_407_p1),8));
    zext_ln349_2_fu_422_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_414_p3),8));
    zext_ln349_3_fu_444_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_i1_0_phi_fu_280_p4),8));
    zext_ln349_4_fu_453_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln349_1_fu_448_p2),64));
    zext_ln349_fu_458_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i1_0_reg_276),64));
    zext_ln357_fu_475_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i2_0_reg_288),64));
    zext_ln369_1_fu_774_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i3_0_reg_311),8));
    zext_ln369_2_fu_783_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln369_reg_938),64));
    zext_ln369_fu_769_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i3_0_reg_311),64));
end behav;
