// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ls_hw (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        state_matrix_address0,
        state_matrix_ce0,
        state_matrix_we0,
        state_matrix_d0,
        state_matrix_q0,
        index1,
        shift,
        arr1_address0,
        arr1_ce0,
        arr1_we0,
        arr1_d0,
        arr1_q0,
        arr2_address0,
        arr2_ce0,
        arr2_we0,
        arr2_d0,
        arr2_q0,
        arr2_address1,
        arr2_ce1,
        arr2_we1,
        arr2_d1,
        arr3_address0,
        arr3_ce0,
        arr3_we0,
        arr3_d0,
        arr3_q0,
        arr3_address1,
        arr3_ce1,
        arr3_q1
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_pp0_stage0 = 13'd2;
parameter    ap_ST_fsm_state4 = 13'd4;
parameter    ap_ST_fsm_state5 = 13'd8;
parameter    ap_ST_fsm_pp1_stage0 = 13'd16;
parameter    ap_ST_fsm_state8 = 13'd32;
parameter    ap_ST_fsm_pp2_stage0 = 13'd64;
parameter    ap_ST_fsm_state11 = 13'd128;
parameter    ap_ST_fsm_pp3_stage0 = 13'd256;
parameter    ap_ST_fsm_pp3_stage1 = 13'd512;
parameter    ap_ST_fsm_state16 = 13'd1024;
parameter    ap_ST_fsm_pp4_stage0 = 13'd2048;
parameter    ap_ST_fsm_state19 = 13'd4096;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] state_matrix_address0;
output   state_matrix_ce0;
output   state_matrix_we0;
output  [7:0] state_matrix_d0;
input  [7:0] state_matrix_q0;
input  [4:0] index1;
input  [5:0] shift;
output  [2:0] arr1_address0;
output   arr1_ce0;
output   arr1_we0;
output  [7:0] arr1_d0;
input  [7:0] arr1_q0;
output  [4:0] arr2_address0;
output   arr2_ce0;
output   arr2_we0;
output  [7:0] arr2_d0;
input  [7:0] arr2_q0;
output  [4:0] arr2_address1;
output   arr2_ce1;
output   arr2_we1;
output  [7:0] arr2_d1;
output  [4:0] arr3_address0;
output   arr3_ce0;
output   arr3_we0;
output  [7:0] arr3_d0;
input  [7:0] arr3_q0;
output  [4:0] arr3_address1;
output   arr3_ce1;
input  [7:0] arr3_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] state_matrix_address0;
reg state_matrix_ce0;
reg state_matrix_we0;
reg[2:0] arr1_address0;
reg arr1_ce0;
reg arr1_we0;
reg[7:0] arr1_d0;
reg[4:0] arr2_address0;
reg arr2_ce0;
reg arr2_we0;
reg arr2_ce1;
reg arr2_we1;
reg[4:0] arr3_address0;
reg arr3_ce0;
reg arr3_we0;
reg[4:0] arr3_address1;
reg arr3_ce1;

(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] i_0_reg_275;
reg   [5:0] count2_0_in_reg_287;
reg   [4:0] i1_0_reg_296;
reg   [5:0] i2_0_reg_308;
reg   [3:0] i_0_i_reg_320;
reg   [3:0] i_0_i_reg_320_pp3_iter1_reg;
wire    ap_CS_fsm_pp3_stage0;
wire    ap_block_state12_pp3_stage0_iter0;
wire    ap_block_state14_pp3_stage0_iter1;
wire    ap_block_pp3_stage0_11001;
reg   [3:0] i3_0_reg_332;
wire   [7:0] add_ln400_fu_383_p2;
reg   [7:0] add_ln400_reg_822;
wire   [0:0] icmp_ln398_fu_389_p2;
reg   [0:0] icmp_ln398_reg_828;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] i_fu_395_p2;
reg   [3:0] i_reg_832;
reg    ap_enable_reg_pp0_iter0;
wire   [4:0] trunc_ln405_fu_420_p1;
reg   [4:0] trunc_ln405_reg_842;
wire    ap_CS_fsm_state4;
wire   [5:0] zext_ln405_fu_423_p1;
wire    ap_CS_fsm_state5;
wire    grp_convert_hex_to_binar_fu_343_ap_ready;
wire    grp_convert_hex_to_binar_fu_343_ap_done;
wire   [5:0] sub_ln412_fu_426_p2;
reg   [5:0] sub_ln412_reg_853;
wire   [0:0] icmp_ln408_fu_432_p2;
reg   [0:0] icmp_ln408_reg_858;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state6_pp1_stage0_iter0;
wire    ap_block_state7_pp1_stage0_iter1;
wire    ap_block_pp1_stage0_11001;
wire  signed [5:0] count2_fu_442_p2;
reg  signed [5:0] count2_reg_862;
reg    ap_enable_reg_pp1_iter0;
wire   [0:0] icmp_ln412_fu_453_p2;
reg   [0:0] icmp_ln412_reg_872;
wire   [4:0] i_5_fu_458_p2;
reg   [4:0] i_5_reg_876;
wire   [5:0] zext_ln420_fu_474_p1;
reg   [5:0] zext_ln420_reg_888;
wire    ap_CS_fsm_state8;
wire   [0:0] tmp_11_fu_483_p3;
reg   [0:0] tmp_11_reg_893;
wire    ap_CS_fsm_pp2_stage0;
wire    ap_block_state9_pp2_stage0_iter0;
wire    ap_block_state10_pp2_stage0_iter1;
wire    ap_block_pp2_stage0_11001;
wire   [0:0] icmp_ln420_fu_491_p2;
reg   [0:0] icmp_ln420_reg_897;
wire   [5:0] i_9_fu_515_p2;
reg   [5:0] i_9_reg_906;
reg    ap_enable_reg_pp2_iter0;
wire   [0:0] icmp_ln114_fu_526_p2;
reg   [0:0] icmp_ln114_reg_911;
reg   [0:0] icmp_ln114_reg_911_pp3_iter1_reg;
wire   [3:0] i_7_fu_532_p2;
reg   [3:0] i_7_reg_915;
reg    ap_enable_reg_pp3_iter0;
wire   [4:0] shl_ln_fu_542_p3;
reg   [4:0] shl_ln_reg_920;
wire   [0:0] grp_fu_351_p2;
reg   [0:0] icmp_ln116_reg_936;
wire    ap_CS_fsm_pp3_stage1;
wire    ap_block_state13_pp3_stage1_iter0;
wire    ap_block_state15_pp3_stage1_iter1;
wire    ap_block_pp3_stage1_11001;
wire   [0:0] grp_fu_357_p2;
reg   [0:0] icmp_ln117_reg_944;
reg   [0:0] icmp_ln118_reg_962;
reg    ap_enable_reg_pp3_iter1;
reg   [0:0] icmp_ln119_reg_969;
wire   [0:0] xor_ln118_fu_628_p2;
reg   [0:0] xor_ln118_reg_978;
wire   [6:0] select_ln118_7_fu_640_p3;
reg   [6:0] select_ln118_7_reg_984;
wire   [0:0] icmp_ln429_fu_787_p2;
reg   [0:0] icmp_ln429_reg_989;
wire    ap_CS_fsm_pp4_stage0;
wire    ap_block_state17_pp4_stage0_iter0;
wire    ap_block_state18_pp4_stage0_iter1;
wire    ap_block_pp4_stage0_11001;
wire   [3:0] i_10_fu_793_p2;
reg    ap_enable_reg_pp4_iter0;
wire   [7:0] add_ln431_fu_808_p2;
reg   [7:0] add_ln431_reg_998;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp1_stage0_subdone;
reg    ap_predicate_tran7to8_state6;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state9;
reg    ap_enable_reg_pp2_iter1;
wire    ap_CS_fsm_state11;
wire    ap_block_pp3_stage0_subdone;
reg    ap_condition_pp3_exit_iter0_state12;
wire    ap_block_pp3_stage1_subdone;
wire    ap_CS_fsm_state16;
wire    ap_block_pp4_stage0_subdone;
reg    ap_condition_pp4_exit_iter0_state17;
reg    ap_enable_reg_pp4_iter1;
wire    grp_convert_hex_to_binar_fu_343_ap_start;
wire    grp_convert_hex_to_binar_fu_343_ap_idle;
wire   [2:0] grp_convert_hex_to_binar_fu_343_hex_address0;
wire    grp_convert_hex_to_binar_fu_343_hex_ce0;
wire   [4:0] grp_convert_hex_to_binar_fu_343_bin_address0;
wire    grp_convert_hex_to_binar_fu_343_bin_ce0;
wire    grp_convert_hex_to_binar_fu_343_bin_we0;
wire   [7:0] grp_convert_hex_to_binar_fu_343_bin_d0;
wire   [4:0] grp_convert_hex_to_binar_fu_343_bin_address1;
wire    grp_convert_hex_to_binar_fu_343_bin_ce1;
wire    grp_convert_hex_to_binar_fu_343_bin_we1;
wire   [7:0] grp_convert_hex_to_binar_fu_343_bin_d1;
reg   [3:0] ap_phi_mux_i_0_phi_fu_279_p4;
wire    ap_block_pp0_stage0;
reg   [5:0] ap_phi_mux_count2_0_in_phi_fu_290_p4;
wire    ap_block_pp1_stage0;
reg   [4:0] ap_phi_mux_i1_0_phi_fu_300_p4;
reg   [5:0] ap_phi_mux_i2_0_phi_fu_312_p4;
wire    ap_block_pp2_stage0;
reg   [3:0] ap_phi_mux_i_0_i_phi_fu_324_p4;
wire    ap_block_pp3_stage0;
reg    grp_convert_hex_to_binar_fu_343_ap_start_reg;
wire   [63:0] zext_ln400_4_fu_410_p1;
wire   [63:0] zext_ln400_fu_415_p1;
wire  signed [63:0] sext_ln410_fu_448_p1;
wire   [63:0] zext_ln410_fu_464_p1;
wire  signed [63:0] sext_ln423_fu_499_p1;
wire   [63:0] zext_ln423_fu_521_p1;
wire   [63:0] zext_ln116_fu_550_p1;
wire   [63:0] zext_ln117_fu_561_p1;
wire   [63:0] zext_ln118_fu_571_p1;
wire    ap_block_pp3_stage1;
wire   [63:0] zext_ln119_fu_581_p1;
wire   [63:0] zext_ln119_2_fu_648_p1;
wire   [63:0] zext_ln431_fu_799_p1;
wire    ap_block_pp4_stage0;
wire   [63:0] zext_ln431_2_fu_813_p1;
reg   [31:0] count_1_fu_128;
wire   [31:0] count_fu_504_p2;
wire   [7:0] zext_ln118_2_fu_782_p1;
wire   [3:0] trunc_ln400_fu_363_p1;
wire   [6:0] tmp_4_fu_371_p3;
wire   [7:0] zext_ln400_2_fu_379_p1;
wire   [7:0] zext_ln400_1_fu_367_p1;
wire   [7:0] zext_ln400_3_fu_401_p1;
wire   [7:0] add_ln400_1_fu_405_p2;
wire   [5:0] zext_ln407_fu_438_p1;
wire   [4:0] xor_ln420_fu_469_p2;
wire  signed [31:0] sext_ln423_fu_499_p0;
wire  signed [31:0] count_fu_504_p0;
wire   [2:0] trunc_ln116_fu_538_p1;
wire   [4:0] or_ln117_fu_555_p2;
wire   [4:0] or_ln118_fu_566_p2;
wire   [4:0] or_ln119_fu_576_p2;
wire   [0:0] and_ln117_fu_610_p2;
wire   [0:0] and_ln118_fu_614_p2;
wire   [6:0] select_ln119_fu_586_p3;
wire   [6:0] select_ln155_fu_602_p3;
wire   [0:0] and_ln118_7_fu_634_p2;
wire   [6:0] select_ln123_fu_594_p3;
wire   [6:0] select_ln118_fu_620_p3;
wire   [0:0] xor_ln117_fu_688_p2;
wire   [0:0] and_ln117_3_fu_693_p2;
wire   [0:0] and_ln118_8_fu_698_p2;
wire   [6:0] select_ln129_fu_653_p3;
wire   [0:0] and_ln118_9_fu_710_p2;
wire   [6:0] select_ln133_fu_660_p3;
wire   [6:0] select_ln118_8_fu_703_p3;
wire   [0:0] xor_ln116_fu_723_p2;
wire   [0:0] and_ln117_4_fu_728_p2;
wire   [0:0] and_ln118_10_fu_733_p2;
wire   [6:0] select_ln141_fu_667_p3;
wire   [6:0] select_ln118_9_fu_715_p3;
wire   [0:0] and_ln118_11_fu_746_p2;
wire   [6:0] select_ln145_fu_674_p3;
wire   [6:0] select_ln118_10_fu_738_p3;
wire   [0:0] or_ln117_2_fu_759_p2;
wire   [0:0] xor_ln117_2_fu_763_p2;
wire   [0:0] and_ln118_12_fu_769_p2;
wire   [6:0] select_ln151_fu_681_p3;
wire   [6:0] select_ln118_11_fu_751_p3;
wire   [6:0] select_ln118_12_fu_774_p3;
wire   [7:0] zext_ln431_1_fu_804_p1;
wire    ap_CS_fsm_state19;
reg   [12:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_idle_pp3;
wire    ap_enable_pp3;
reg    ap_idle_pp4;
wire    ap_enable_pp4;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
#0 ap_enable_reg_pp4_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp4_iter1 = 1'b0;
#0 grp_convert_hex_to_binar_fu_343_ap_start_reg = 1'b0;
end

convert_hex_to_binar grp_convert_hex_to_binar_fu_343(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_convert_hex_to_binar_fu_343_ap_start),
    .ap_done(grp_convert_hex_to_binar_fu_343_ap_done),
    .ap_idle(grp_convert_hex_to_binar_fu_343_ap_idle),
    .ap_ready(grp_convert_hex_to_binar_fu_343_ap_ready),
    .hex_address0(grp_convert_hex_to_binar_fu_343_hex_address0),
    .hex_ce0(grp_convert_hex_to_binar_fu_343_hex_ce0),
    .hex_q0(arr1_q0),
    .bin_address0(grp_convert_hex_to_binar_fu_343_bin_address0),
    .bin_ce0(grp_convert_hex_to_binar_fu_343_bin_ce0),
    .bin_we0(grp_convert_hex_to_binar_fu_343_bin_we0),
    .bin_d0(grp_convert_hex_to_binar_fu_343_bin_d0),
    .bin_address1(grp_convert_hex_to_binar_fu_343_bin_address1),
    .bin_ce1(grp_convert_hex_to_binar_fu_343_bin_ce1),
    .bin_we1(grp_convert_hex_to_binar_fu_343_bin_we1),
    .bin_d1(grp_convert_hex_to_binar_fu_343_bin_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (ap_predicate_tran7to8_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (grp_convert_hex_to_binar_fu_343_ap_done == 1'b1))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (grp_convert_hex_to_binar_fu_343_ap_done == 1'b1))) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state9) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state9))) begin
            ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state9);
        end else if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp3_stage0_subdone) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b1 == ap_condition_pp3_exit_iter0_state12))) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state11)) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp3_stage1_subdone) & (1'b1 == ap_CS_fsm_pp3_stage1))) begin
            ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
        end else if ((1'b1 == ap_CS_fsm_state11)) begin
            ap_enable_reg_pp3_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp4_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp4_stage0_subdone) & (1'b1 == ap_condition_pp4_exit_iter0_state17) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
            ap_enable_reg_pp4_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state16)) begin
            ap_enable_reg_pp4_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp4_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp4_stage0_subdone) & (1'b1 == ap_condition_pp4_exit_iter0_state17))) begin
            ap_enable_reg_pp4_iter1 <= (1'b1 ^ ap_condition_pp4_exit_iter0_state17);
        end else if ((1'b0 == ap_block_pp4_stage0_subdone)) begin
            ap_enable_reg_pp4_iter1 <= ap_enable_reg_pp4_iter0;
        end else if ((1'b1 == ap_CS_fsm_state16)) begin
            ap_enable_reg_pp4_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_convert_hex_to_binar_fu_343_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_convert_hex_to_binar_fu_343_ap_start_reg <= 1'b1;
        end else if ((grp_convert_hex_to_binar_fu_343_ap_ready == 1'b1)) begin
            grp_convert_hex_to_binar_fu_343_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln412_reg_872 == 1'd0) & (icmp_ln408_reg_858 == 1'd0))) begin
        count2_0_in_reg_287 <= count2_reg_862;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_convert_hex_to_binar_fu_343_ap_done == 1'b1))) begin
        count2_0_in_reg_287 <= zext_ln405_fu_423_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001) & (icmp_ln420_fu_491_p2 == 1'd0) & (tmp_11_fu_483_p3 == 1'd0))) begin
        count_1_fu_128 <= count_fu_504_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        count_1_fu_128 <= 32'd31;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln412_reg_872 == 1'd0) & (icmp_ln408_reg_858 == 1'd0))) begin
        i1_0_reg_296 <= i_5_reg_876;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_convert_hex_to_binar_fu_343_ap_done == 1'b1))) begin
        i1_0_reg_296 <= 5'd31;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001) & (tmp_11_reg_893 == 1'd0))) begin
        i2_0_reg_308 <= i_9_reg_906;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        i2_0_reg_308 <= 6'd31;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        i3_0_reg_332 <= 4'd0;
    end else if (((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (icmp_ln429_fu_787_p2 == 1'd0))) begin
        i3_0_reg_332 <= i_10_fu_793_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        i_0_i_reg_320 <= 4'd0;
    end else if (((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln114_reg_911 == 1'd0))) begin
        i_0_i_reg_320 <= i_7_reg_915;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln398_reg_828 == 1'd0))) begin
        i_0_reg_275 <= i_reg_832;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_275 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        add_ln400_reg_822 <= add_ln400_fu_383_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (1'b1 == ap_CS_fsm_pp4_stage0) & (icmp_ln429_fu_787_p2 == 1'd0))) begin
        add_ln431_reg_998 <= add_ln431_fu_808_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln408_fu_432_p2 == 1'd0))) begin
        count2_reg_862 <= count2_fu_442_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        i_0_i_reg_320_pp3_iter1_reg <= i_0_i_reg_320;
        icmp_ln114_reg_911 <= icmp_ln114_fu_526_p2;
        icmp_ln114_reg_911_pp3_iter1_reg <= icmp_ln114_reg_911;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln412_fu_453_p2 == 1'd0) & (icmp_ln408_fu_432_p2 == 1'd0))) begin
        i_5_reg_876 <= i_5_fu_458_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1))) begin
        i_7_reg_915 <= i_7_fu_532_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001) & (tmp_11_fu_483_p3 == 1'd0))) begin
        i_9_reg_906 <= i_9_fu_515_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_reg_832 <= i_fu_395_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage1_11001) & (1'b1 == ap_CS_fsm_pp3_stage1) & (ap_enable_reg_pp3_iter0 == 1'b1) & (icmp_ln114_reg_911 == 1'd0))) begin
        icmp_ln116_reg_936 <= grp_fu_351_p2;
        icmp_ln117_reg_944 <= grp_fu_357_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln114_reg_911 == 1'd0))) begin
        icmp_ln118_reg_962 <= grp_fu_357_p2;
        icmp_ln119_reg_969 <= grp_fu_351_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln398_reg_828 <= icmp_ln398_fu_389_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        icmp_ln408_reg_858 <= icmp_ln408_fu_432_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln408_fu_432_p2 == 1'd0))) begin
        icmp_ln412_reg_872 <= icmp_ln412_fu_453_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001) & (tmp_11_fu_483_p3 == 1'd0))) begin
        icmp_ln420_reg_897 <= icmp_ln420_fu_491_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        icmp_ln429_reg_989 <= icmp_ln429_fu_787_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0) & (icmp_ln114_reg_911 == 1'd0))) begin
        select_ln118_7_reg_984[2 : 0] <= select_ln118_7_fu_640_p3[2 : 0];
select_ln118_7_reg_984[4] <= select_ln118_7_fu_640_p3[4];
select_ln118_7_reg_984[6] <= select_ln118_7_fu_640_p3[6];
        xor_ln118_reg_978 <= xor_ln118_fu_628_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0) & (icmp_ln114_fu_526_p2 == 1'd0))) begin
        shl_ln_reg_920[4 : 2] <= shl_ln_fu_542_p3[4 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_convert_hex_to_binar_fu_343_ap_done == 1'b1))) begin
        sub_ln412_reg_853 <= sub_ln412_fu_426_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        tmp_11_reg_893 <= ap_phi_mux_i2_0_phi_fu_312_p4[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        trunc_ln405_reg_842 <= trunc_ln405_fu_420_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        zext_ln420_reg_888[4 : 0] <= zext_ln420_fu_474_p1[4 : 0];
    end
end

always @ (*) begin
    if ((icmp_ln398_fu_389_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_11_fu_483_p3 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state9 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state9 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln114_fu_526_p2 == 1'd1)) begin
        ap_condition_pp3_exit_iter0_state12 = 1'b1;
    end else begin
        ap_condition_pp3_exit_iter0_state12 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln429_fu_787_p2 == 1'd1)) begin
        ap_condition_pp4_exit_iter0_state17 = 1'b1;
    end else begin
        ap_condition_pp4_exit_iter0_state17 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b0))) begin
        ap_idle_pp3 = 1'b1;
    end else begin
        ap_idle_pp3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp4_iter1 == 1'b0) & (ap_enable_reg_pp4_iter0 == 1'b0))) begin
        ap_idle_pp4 = 1'b1;
    end else begin
        ap_idle_pp4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln412_reg_872 == 1'd0) & (icmp_ln408_reg_858 == 1'd0))) begin
        ap_phi_mux_count2_0_in_phi_fu_290_p4 = count2_reg_862;
    end else begin
        ap_phi_mux_count2_0_in_phi_fu_290_p4 = count2_0_in_reg_287;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln412_reg_872 == 1'd0) & (icmp_ln408_reg_858 == 1'd0))) begin
        ap_phi_mux_i1_0_phi_fu_300_p4 = i_5_reg_876;
    end else begin
        ap_phi_mux_i1_0_phi_fu_300_p4 = i1_0_reg_296;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (tmp_11_reg_893 == 1'd0))) begin
        ap_phi_mux_i2_0_phi_fu_312_p4 = i_9_reg_906;
    end else begin
        ap_phi_mux_i2_0_phi_fu_312_p4 = i2_0_reg_308;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln114_reg_911 == 1'd0))) begin
        ap_phi_mux_i_0_i_phi_fu_324_p4 = i_7_reg_915;
    end else begin
        ap_phi_mux_i_0_i_phi_fu_324_p4 = i_0_i_reg_320;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln398_reg_828 == 1'd0))) begin
        ap_phi_mux_i_0_phi_fu_279_p4 = i_reg_832;
    end else begin
        ap_phi_mux_i_0_phi_fu_279_p4 = i_0_reg_275;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp4_stage0) & (ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        arr1_address0 = zext_ln431_fu_799_p1;
    end else if (((1'b0 == ap_block_pp3_stage1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage1))) begin
        arr1_address0 = zext_ln119_2_fu_648_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr1_address0 = zext_ln400_fu_415_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        arr1_address0 = grp_convert_hex_to_binar_fu_343_hex_address0;
    end else begin
        arr1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0)) | ((1'b0 == ap_block_pp3_stage1_11001) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        arr1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        arr1_ce0 = grp_convert_hex_to_binar_fu_343_hex_ce0;
    end else begin
        arr1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage1))) begin
        arr1_d0 = zext_ln118_2_fu_782_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr1_d0 = state_matrix_q0;
    end else begin
        arr1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp3_stage1_11001) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage1) & (icmp_ln114_reg_911_pp3_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln398_reg_828 == 1'd0)))) begin
        arr1_we0 = 1'b1;
    end else begin
        arr1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        arr2_address0 = sext_ln423_fu_499_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        arr2_address0 = sext_ln410_fu_448_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        arr2_address0 = grp_convert_hex_to_binar_fu_343_bin_address0;
    end else begin
        arr2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        arr2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        arr2_ce0 = grp_convert_hex_to_binar_fu_343_bin_ce0;
    end else begin
        arr2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        arr2_ce1 = grp_convert_hex_to_binar_fu_343_bin_ce1;
    end else begin
        arr2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        arr2_we0 = grp_convert_hex_to_binar_fu_343_bin_we0;
    end else begin
        arr2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        arr2_we1 = grp_convert_hex_to_binar_fu_343_bin_we1;
    end else begin
        arr2_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage1) & (1'b1 == ap_CS_fsm_pp3_stage1) & (ap_enable_reg_pp3_iter0 == 1'b1))) begin
        arr3_address0 = zext_ln119_fu_581_p1;
    end else if (((1'b0 == ap_block_pp3_stage0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1))) begin
        arr3_address0 = zext_ln116_fu_550_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        arr3_address0 = zext_ln423_fu_521_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        arr3_address0 = zext_ln410_fu_464_p1;
    end else begin
        arr3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp3_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp3_stage1) & (1'b1 == ap_CS_fsm_pp3_stage1))) begin
            arr3_address1 = zext_ln118_fu_571_p1;
        end else if (((1'b0 == ap_block_pp3_stage0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
            arr3_address1 = zext_ln117_fu_561_p1;
        end else begin
            arr3_address1 = 'bx;
        end
    end else begin
        arr3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1)) | ((1'b0 == ap_block_pp3_stage1_11001) & (1'b1 == ap_CS_fsm_pp3_stage1) & (ap_enable_reg_pp3_iter0 == 1'b1)) | ((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        arr3_ce0 = 1'b1;
    end else begin
        arr3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1)) | ((1'b0 == ap_block_pp3_stage1_11001) & (1'b1 == ap_CS_fsm_pp3_stage1) & (ap_enable_reg_pp3_iter0 == 1'b1)))) begin
        arr3_ce1 = 1'b1;
    end else begin
        arr3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001) & (icmp_ln420_reg_897 == 1'd0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln408_reg_858 == 1'd0)))) begin
        arr3_we0 = 1'b1;
    end else begin
        arr3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp4_stage0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        state_matrix_address0 = zext_ln431_2_fu_813_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        state_matrix_address0 = zext_ln400_4_fu_410_p1;
    end else begin
        state_matrix_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        state_matrix_ce0 = 1'b1;
    end else begin
        state_matrix_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (icmp_ln429_reg_989 == 1'd0))) begin
        state_matrix_we0 = 1'b1;
    end else begin
        state_matrix_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln398_fu_389_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln398_fu_389_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_convert_hex_to_binar_fu_343_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if (~((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter0 == 1'b1) & (tmp_11_fu_483_p3 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter0 == 1'b1) & (tmp_11_fu_483_p3 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_pp3_stage0;
        end
        ap_ST_fsm_pp3_stage0 : begin
            if ((~((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter1 == 1'b0) & (icmp_ln114_fu_526_p2 == 1'd1) & (ap_enable_reg_pp3_iter0 == 1'b1)) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage1;
            end else if (((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter1 == 1'b0) & (icmp_ln114_fu_526_p2 == 1'd1) & (ap_enable_reg_pp3_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        ap_ST_fsm_pp3_stage1 : begin
            if ((~((1'b0 == ap_block_pp3_stage1_subdone) & (ap_enable_reg_pp3_iter0 == 1'b0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage1)) & (1'b0 == ap_block_pp3_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if (((1'b0 == ap_block_pp3_stage1_subdone) & (ap_enable_reg_pp3_iter0 == 1'b0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage1;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_pp4_stage0;
        end
        ap_ST_fsm_pp4_stage0 : begin
            if (~((1'b0 == ap_block_pp4_stage0_subdone) & (icmp_ln429_fu_787_p2 == 1'd1) & (ap_enable_reg_pp4_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end else if (((1'b0 == ap_block_pp4_stage0_subdone) & (icmp_ln429_fu_787_p2 == 1'd1) & (ap_enable_reg_pp4_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln400_1_fu_405_p2 = (add_ln400_reg_822 + zext_ln400_3_fu_401_p1);

assign add_ln400_fu_383_p2 = (zext_ln400_2_fu_379_p1 + zext_ln400_1_fu_367_p1);

assign add_ln431_fu_808_p2 = (add_ln400_reg_822 + zext_ln431_1_fu_804_p1);

assign and_ln117_3_fu_693_p2 = (xor_ln117_fu_688_p2 & icmp_ln116_reg_936);

assign and_ln117_4_fu_728_p2 = (xor_ln116_fu_723_p2 & icmp_ln117_reg_944);

assign and_ln117_fu_610_p2 = (icmp_ln117_reg_944 & icmp_ln116_reg_936);

assign and_ln118_10_fu_733_p2 = (icmp_ln118_reg_962 & and_ln117_4_fu_728_p2);

assign and_ln118_11_fu_746_p2 = (xor_ln118_reg_978 & and_ln117_4_fu_728_p2);

assign and_ln118_12_fu_769_p2 = (xor_ln117_2_fu_763_p2 & icmp_ln118_reg_962);

assign and_ln118_7_fu_634_p2 = (xor_ln118_fu_628_p2 & and_ln117_fu_610_p2);

assign and_ln118_8_fu_698_p2 = (icmp_ln118_reg_962 & and_ln117_3_fu_693_p2);

assign and_ln118_9_fu_710_p2 = (xor_ln118_reg_978 & and_ln117_3_fu_693_p2);

assign and_ln118_fu_614_p2 = (grp_fu_357_p2 & and_ln117_fu_610_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp3_stage1 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_pp4_stage0 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp4_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp4_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp4_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp3_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp3_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp3_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp3_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp4_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp4_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_enable_pp3 = (ap_idle_pp3 ^ 1'b1);

assign ap_enable_pp4 = (ap_idle_pp4 ^ 1'b1);

always @ (*) begin
    ap_predicate_tran7to8_state6 = ((icmp_ln412_fu_453_p2 == 1'd1) | (icmp_ln408_fu_432_p2 == 1'd1));
end

assign arr2_address1 = grp_convert_hex_to_binar_fu_343_bin_address1;

assign arr2_d0 = grp_convert_hex_to_binar_fu_343_bin_d0;

assign arr2_d1 = grp_convert_hex_to_binar_fu_343_bin_d1;

assign arr3_d0 = arr2_q0;

assign count2_fu_442_p2 = ($signed(ap_phi_mux_count2_0_in_phi_fu_290_p4) + $signed(6'd63));

assign count_fu_504_p0 = count_1_fu_128;

assign count_fu_504_p2 = ($signed(count_fu_504_p0) + $signed(32'd4294967295));

assign grp_convert_hex_to_binar_fu_343_ap_start = grp_convert_hex_to_binar_fu_343_ap_start_reg;

assign grp_fu_351_p2 = ((arr3_q0 == 8'd48) ? 1'b1 : 1'b0);

assign grp_fu_357_p2 = ((arr3_q1 == 8'd48) ? 1'b1 : 1'b0);

assign i_10_fu_793_p2 = (i3_0_reg_332 + 4'd1);

assign i_5_fu_458_p2 = ($signed(ap_phi_mux_i1_0_phi_fu_300_p4) + $signed(5'd31));

assign i_7_fu_532_p2 = (ap_phi_mux_i_0_i_phi_fu_324_p4 + 4'd1);

assign i_9_fu_515_p2 = ($signed(ap_phi_mux_i2_0_phi_fu_312_p4) + $signed(6'd63));

assign i_fu_395_p2 = (ap_phi_mux_i_0_phi_fu_279_p4 + 4'd1);

assign icmp_ln114_fu_526_p2 = ((ap_phi_mux_i_0_i_phi_fu_324_p4 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln398_fu_389_p2 = ((ap_phi_mux_i_0_phi_fu_279_p4 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln408_fu_432_p2 = ((ap_phi_mux_i1_0_phi_fu_300_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln412_fu_453_p2 = ((zext_ln407_fu_438_p1 == sub_ln412_reg_853) ? 1'b1 : 1'b0);

assign icmp_ln420_fu_491_p2 = (($signed(ap_phi_mux_i2_0_phi_fu_312_p4) > $signed(zext_ln420_reg_888)) ? 1'b1 : 1'b0);

assign icmp_ln429_fu_787_p2 = ((i3_0_reg_332 == 4'd8) ? 1'b1 : 1'b0);

assign or_ln117_2_fu_759_p2 = (icmp_ln117_reg_944 | icmp_ln116_reg_936);

assign or_ln117_fu_555_p2 = (shl_ln_fu_542_p3 | 5'd1);

assign or_ln118_fu_566_p2 = (shl_ln_reg_920 | 5'd2);

assign or_ln119_fu_576_p2 = (shl_ln_reg_920 | 5'd3);

assign select_ln118_10_fu_738_p3 = ((and_ln118_10_fu_733_p2[0:0] === 1'b1) ? select_ln141_fu_667_p3 : select_ln118_9_fu_715_p3);

assign select_ln118_11_fu_751_p3 = ((and_ln118_11_fu_746_p2[0:0] === 1'b1) ? select_ln145_fu_674_p3 : select_ln118_10_fu_738_p3);

assign select_ln118_12_fu_774_p3 = ((and_ln118_12_fu_769_p2[0:0] === 1'b1) ? select_ln151_fu_681_p3 : select_ln118_11_fu_751_p3);

assign select_ln118_7_fu_640_p3 = ((and_ln118_7_fu_634_p2[0:0] === 1'b1) ? select_ln123_fu_594_p3 : select_ln118_fu_620_p3);

assign select_ln118_8_fu_703_p3 = ((and_ln118_8_fu_698_p2[0:0] === 1'b1) ? select_ln129_fu_653_p3 : select_ln118_7_reg_984);

assign select_ln118_9_fu_715_p3 = ((and_ln118_9_fu_710_p2[0:0] === 1'b1) ? select_ln133_fu_660_p3 : select_ln118_8_fu_703_p3);

assign select_ln118_fu_620_p3 = ((and_ln118_fu_614_p2[0:0] === 1'b1) ? select_ln119_fu_586_p3 : select_ln155_fu_602_p3);

assign select_ln119_fu_586_p3 = ((grp_fu_351_p2[0:0] === 1'b1) ? 7'd48 : 7'd49);

assign select_ln123_fu_594_p3 = ((grp_fu_351_p2[0:0] === 1'b1) ? 7'd50 : 7'd51);

assign select_ln129_fu_653_p3 = ((icmp_ln119_reg_969[0:0] === 1'b1) ? 7'd52 : 7'd53);

assign select_ln133_fu_660_p3 = ((icmp_ln119_reg_969[0:0] === 1'b1) ? 7'd54 : 7'd55);

assign select_ln141_fu_667_p3 = ((icmp_ln119_reg_969[0:0] === 1'b1) ? 7'd56 : 7'd57);

assign select_ln145_fu_674_p3 = ((icmp_ln119_reg_969[0:0] === 1'b1) ? 7'd97 : 7'd98);

assign select_ln151_fu_681_p3 = ((icmp_ln119_reg_969[0:0] === 1'b1) ? 7'd99 : 7'd100);

assign select_ln155_fu_602_p3 = ((grp_fu_351_p2[0:0] === 1'b1) ? 7'd101 : 7'd102);

assign sext_ln410_fu_448_p1 = count2_fu_442_p2;

assign sext_ln423_fu_499_p0 = count_1_fu_128;

assign sext_ln423_fu_499_p1 = sext_ln423_fu_499_p0;

assign shl_ln_fu_542_p3 = {{trunc_ln116_fu_538_p1}, {2'd0}};

assign state_matrix_d0 = arr1_q0;

assign sub_ln412_fu_426_p2 = ($signed(6'd32) - $signed(zext_ln405_fu_423_p1));

assign tmp_11_fu_483_p3 = ap_phi_mux_i2_0_phi_fu_312_p4[32'd5];

assign tmp_4_fu_371_p3 = {{trunc_ln400_fu_363_p1}, {3'd0}};

assign trunc_ln116_fu_538_p1 = ap_phi_mux_i_0_i_phi_fu_324_p4[2:0];

assign trunc_ln400_fu_363_p1 = index1[3:0];

assign trunc_ln405_fu_420_p1 = shift[4:0];

assign xor_ln116_fu_723_p2 = (icmp_ln116_reg_936 ^ 1'd1);

assign xor_ln117_2_fu_763_p2 = (or_ln117_2_fu_759_p2 ^ 1'd1);

assign xor_ln117_fu_688_p2 = (icmp_ln117_reg_944 ^ 1'd1);

assign xor_ln118_fu_628_p2 = (grp_fu_357_p2 ^ 1'd1);

assign xor_ln420_fu_469_p2 = (trunc_ln405_reg_842 ^ 5'd31);

assign zext_ln116_fu_550_p1 = shl_ln_fu_542_p3;

assign zext_ln117_fu_561_p1 = or_ln117_fu_555_p2;

assign zext_ln118_2_fu_782_p1 = select_ln118_12_fu_774_p3;

assign zext_ln118_fu_571_p1 = or_ln118_fu_566_p2;

assign zext_ln119_2_fu_648_p1 = i_0_i_reg_320_pp3_iter1_reg;

assign zext_ln119_fu_581_p1 = or_ln119_fu_576_p2;

assign zext_ln400_1_fu_367_p1 = trunc_ln400_fu_363_p1;

assign zext_ln400_2_fu_379_p1 = tmp_4_fu_371_p3;

assign zext_ln400_3_fu_401_p1 = ap_phi_mux_i_0_phi_fu_279_p4;

assign zext_ln400_4_fu_410_p1 = add_ln400_1_fu_405_p2;

assign zext_ln400_fu_415_p1 = i_0_reg_275;

assign zext_ln405_fu_423_p1 = trunc_ln405_reg_842;

assign zext_ln407_fu_438_p1 = ap_phi_mux_i1_0_phi_fu_300_p4;

assign zext_ln410_fu_464_p1 = i1_0_reg_296;

assign zext_ln420_fu_474_p1 = xor_ln420_fu_469_p2;

assign zext_ln423_fu_521_p1 = i2_0_reg_308;

assign zext_ln431_1_fu_804_p1 = i3_0_reg_332;

assign zext_ln431_2_fu_813_p1 = add_ln431_reg_998;

assign zext_ln431_fu_799_p1 = i3_0_reg_332;

always @ (posedge ap_clk) begin
    zext_ln420_reg_888[5] <= 1'b0;
    shl_ln_reg_920[1:0] <= 2'b00;
    select_ln118_7_reg_984[3] <= 1'b0;
    select_ln118_7_reg_984[5] <= 1'b1;
end

endmodule //ls_hw
