// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "convert_hex_to_binar_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic convert_hex_to_binar_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<1> convert_hex_to_binar_1::ap_const_lv1_1 = "1";
const bool convert_hex_to_binar_1::ap_const_boolean_1 = true;
const sc_lv<1> convert_hex_to_binar_1::ap_const_lv1_0 = "0";
const sc_lv<5> convert_hex_to_binar_1::ap_const_lv5_10 = "10000";
const sc_lv<5> convert_hex_to_binar_1::ap_const_lv5_11 = "10001";
const sc_lv<8> convert_hex_to_binar_1::ap_const_lv8_30 = "110000";
const sc_lv<8> convert_hex_to_binar_1::ap_const_lv8_31 = "110001";
const sc_lv<8> convert_hex_to_binar_1::ap_const_lv8_32 = "110010";
const sc_lv<8> convert_hex_to_binar_1::ap_const_lv8_33 = "110011";
const sc_lv<8> convert_hex_to_binar_1::ap_const_lv8_34 = "110100";
const sc_lv<8> convert_hex_to_binar_1::ap_const_lv8_35 = "110101";
const sc_lv<8> convert_hex_to_binar_1::ap_const_lv8_36 = "110110";
const sc_lv<8> convert_hex_to_binar_1::ap_const_lv8_37 = "110111";
const sc_lv<8> convert_hex_to_binar_1::ap_const_lv8_38 = "111000";
const sc_lv<8> convert_hex_to_binar_1::ap_const_lv8_39 = "111001";
const sc_lv<8> convert_hex_to_binar_1::ap_const_lv8_61 = "1100001";
const sc_lv<8> convert_hex_to_binar_1::ap_const_lv8_62 = "1100010";
const sc_lv<8> convert_hex_to_binar_1::ap_const_lv8_63 = "1100011";
const sc_lv<8> convert_hex_to_binar_1::ap_const_lv8_64 = "1100100";
const sc_lv<8> convert_hex_to_binar_1::ap_const_lv8_65 = "1100101";
const sc_lv<8> convert_hex_to_binar_1::ap_const_lv8_66 = "1100110";
const sc_logic convert_hex_to_binar_1::ap_const_logic_0 = sc_dt::Log_0;

convert_hex_to_binar_1::convert_hex_to_binar_1(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_phi_mux_bin_0_15_phi_fu_184_p30);
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );
    sensitive << ( icmp_ln96_fu_342_p2 );
    sensitive << ( icmp_ln97_fu_348_p2 );
    sensitive << ( icmp_ln98_fu_354_p2 );
    sensitive << ( icmp_ln99_fu_360_p2 );
    sensitive << ( icmp_ln100_fu_366_p2 );
    sensitive << ( icmp_ln101_fu_372_p2 );
    sensitive << ( icmp_ln102_fu_378_p2 );
    sensitive << ( icmp_ln103_fu_384_p2 );
    sensitive << ( icmp_ln104_fu_390_p2 );
    sensitive << ( icmp_ln105_fu_396_p2 );
    sensitive << ( icmp_ln106_fu_402_p2 );
    sensitive << ( icmp_ln107_fu_408_p2 );

    SC_METHOD(thread_ap_phi_mux_bin_1_15_phi_fu_134_p30);
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );
    sensitive << ( icmp_ln96_fu_342_p2 );
    sensitive << ( icmp_ln97_fu_348_p2 );
    sensitive << ( icmp_ln98_fu_354_p2 );
    sensitive << ( icmp_ln99_fu_360_p2 );
    sensitive << ( icmp_ln100_fu_366_p2 );
    sensitive << ( icmp_ln101_fu_372_p2 );
    sensitive << ( icmp_ln102_fu_378_p2 );
    sensitive << ( icmp_ln103_fu_384_p2 );
    sensitive << ( icmp_ln104_fu_390_p2 );
    sensitive << ( icmp_ln105_fu_396_p2 );
    sensitive << ( icmp_ln106_fu_402_p2 );
    sensitive << ( icmp_ln107_fu_408_p2 );

    SC_METHOD(thread_ap_phi_mux_bin_2_15_phi_fu_234_p30);
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );
    sensitive << ( icmp_ln96_fu_342_p2 );
    sensitive << ( icmp_ln97_fu_348_p2 );
    sensitive << ( icmp_ln98_fu_354_p2 );
    sensitive << ( icmp_ln99_fu_360_p2 );
    sensitive << ( icmp_ln100_fu_366_p2 );
    sensitive << ( icmp_ln101_fu_372_p2 );
    sensitive << ( icmp_ln102_fu_378_p2 );
    sensitive << ( icmp_ln103_fu_384_p2 );
    sensitive << ( icmp_ln104_fu_390_p2 );
    sensitive << ( icmp_ln105_fu_396_p2 );
    sensitive << ( icmp_ln106_fu_402_p2 );
    sensitive << ( icmp_ln107_fu_408_p2 );

    SC_METHOD(thread_ap_phi_mux_bin_3_15_phi_fu_284_p30);
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );
    sensitive << ( icmp_ln96_fu_342_p2 );
    sensitive << ( icmp_ln97_fu_348_p2 );
    sensitive << ( icmp_ln98_fu_354_p2 );
    sensitive << ( icmp_ln99_fu_360_p2 );
    sensitive << ( icmp_ln100_fu_366_p2 );
    sensitive << ( icmp_ln101_fu_372_p2 );
    sensitive << ( icmp_ln102_fu_378_p2 );
    sensitive << ( icmp_ln103_fu_384_p2 );
    sensitive << ( icmp_ln104_fu_390_p2 );
    sensitive << ( icmp_ln105_fu_396_p2 );
    sensitive << ( icmp_ln106_fu_402_p2 );
    sensitive << ( icmp_ln107_fu_408_p2 );
    sensitive << ( select_ln108_fu_433_p3 );

    SC_METHOD(thread_ap_phi_mux_write_flag3_15_phi_fu_85_p30);
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );
    sensitive << ( icmp_ln96_fu_342_p2 );
    sensitive << ( icmp_ln97_fu_348_p2 );
    sensitive << ( icmp_ln98_fu_354_p2 );
    sensitive << ( icmp_ln99_fu_360_p2 );
    sensitive << ( icmp_ln100_fu_366_p2 );
    sensitive << ( icmp_ln101_fu_372_p2 );
    sensitive << ( icmp_ln102_fu_378_p2 );
    sensitive << ( icmp_ln103_fu_384_p2 );
    sensitive << ( icmp_ln104_fu_390_p2 );
    sensitive << ( icmp_ln105_fu_396_p2 );
    sensitive << ( icmp_ln106_fu_402_p2 );
    sensitive << ( icmp_ln107_fu_408_p2 );
    sensitive << ( or_ln108_fu_426_p2 );

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( select_ln111_fu_474_p3 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( select_ln111_1_fu_482_p3 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( select_ln111_2_fu_490_p3 );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( select_ln111_3_fu_498_p3 );

    SC_METHOD(thread_icmp_ln100_fu_366_p2);
    sensitive << ( p_read );
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );
    sensitive << ( icmp_ln96_fu_342_p2 );
    sensitive << ( icmp_ln97_fu_348_p2 );
    sensitive << ( icmp_ln98_fu_354_p2 );
    sensitive << ( icmp_ln99_fu_360_p2 );

    SC_METHOD(thread_icmp_ln101_fu_372_p2);
    sensitive << ( p_read );
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );
    sensitive << ( icmp_ln96_fu_342_p2 );
    sensitive << ( icmp_ln97_fu_348_p2 );
    sensitive << ( icmp_ln98_fu_354_p2 );
    sensitive << ( icmp_ln99_fu_360_p2 );
    sensitive << ( icmp_ln100_fu_366_p2 );

    SC_METHOD(thread_icmp_ln102_fu_378_p2);
    sensitive << ( p_read );
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );
    sensitive << ( icmp_ln96_fu_342_p2 );
    sensitive << ( icmp_ln97_fu_348_p2 );
    sensitive << ( icmp_ln98_fu_354_p2 );
    sensitive << ( icmp_ln99_fu_360_p2 );
    sensitive << ( icmp_ln100_fu_366_p2 );
    sensitive << ( icmp_ln101_fu_372_p2 );

    SC_METHOD(thread_icmp_ln103_fu_384_p2);
    sensitive << ( p_read );
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );
    sensitive << ( icmp_ln96_fu_342_p2 );
    sensitive << ( icmp_ln97_fu_348_p2 );
    sensitive << ( icmp_ln98_fu_354_p2 );
    sensitive << ( icmp_ln99_fu_360_p2 );
    sensitive << ( icmp_ln100_fu_366_p2 );
    sensitive << ( icmp_ln101_fu_372_p2 );
    sensitive << ( icmp_ln102_fu_378_p2 );

    SC_METHOD(thread_icmp_ln104_fu_390_p2);
    sensitive << ( p_read );
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );
    sensitive << ( icmp_ln96_fu_342_p2 );
    sensitive << ( icmp_ln97_fu_348_p2 );
    sensitive << ( icmp_ln98_fu_354_p2 );
    sensitive << ( icmp_ln99_fu_360_p2 );
    sensitive << ( icmp_ln100_fu_366_p2 );
    sensitive << ( icmp_ln101_fu_372_p2 );
    sensitive << ( icmp_ln102_fu_378_p2 );
    sensitive << ( icmp_ln103_fu_384_p2 );

    SC_METHOD(thread_icmp_ln105_fu_396_p2);
    sensitive << ( p_read );
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );
    sensitive << ( icmp_ln96_fu_342_p2 );
    sensitive << ( icmp_ln97_fu_348_p2 );
    sensitive << ( icmp_ln98_fu_354_p2 );
    sensitive << ( icmp_ln99_fu_360_p2 );
    sensitive << ( icmp_ln100_fu_366_p2 );
    sensitive << ( icmp_ln101_fu_372_p2 );
    sensitive << ( icmp_ln102_fu_378_p2 );
    sensitive << ( icmp_ln103_fu_384_p2 );
    sensitive << ( icmp_ln104_fu_390_p2 );

    SC_METHOD(thread_icmp_ln106_fu_402_p2);
    sensitive << ( p_read );
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );
    sensitive << ( icmp_ln96_fu_342_p2 );
    sensitive << ( icmp_ln97_fu_348_p2 );
    sensitive << ( icmp_ln98_fu_354_p2 );
    sensitive << ( icmp_ln99_fu_360_p2 );
    sensitive << ( icmp_ln100_fu_366_p2 );
    sensitive << ( icmp_ln101_fu_372_p2 );
    sensitive << ( icmp_ln102_fu_378_p2 );
    sensitive << ( icmp_ln103_fu_384_p2 );
    sensitive << ( icmp_ln104_fu_390_p2 );
    sensitive << ( icmp_ln105_fu_396_p2 );

    SC_METHOD(thread_icmp_ln107_fu_408_p2);
    sensitive << ( p_read );
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );
    sensitive << ( icmp_ln96_fu_342_p2 );
    sensitive << ( icmp_ln97_fu_348_p2 );
    sensitive << ( icmp_ln98_fu_354_p2 );
    sensitive << ( icmp_ln99_fu_360_p2 );
    sensitive << ( icmp_ln100_fu_366_p2 );
    sensitive << ( icmp_ln101_fu_372_p2 );
    sensitive << ( icmp_ln102_fu_378_p2 );
    sensitive << ( icmp_ln103_fu_384_p2 );
    sensitive << ( icmp_ln104_fu_390_p2 );
    sensitive << ( icmp_ln105_fu_396_p2 );
    sensitive << ( icmp_ln106_fu_402_p2 );

    SC_METHOD(thread_icmp_ln108_fu_414_p2);
    sensitive << ( p_read );
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );
    sensitive << ( icmp_ln96_fu_342_p2 );
    sensitive << ( icmp_ln97_fu_348_p2 );
    sensitive << ( icmp_ln98_fu_354_p2 );
    sensitive << ( icmp_ln99_fu_360_p2 );
    sensitive << ( icmp_ln100_fu_366_p2 );
    sensitive << ( icmp_ln101_fu_372_p2 );
    sensitive << ( icmp_ln102_fu_378_p2 );
    sensitive << ( icmp_ln103_fu_384_p2 );
    sensitive << ( icmp_ln104_fu_390_p2 );
    sensitive << ( icmp_ln105_fu_396_p2 );
    sensitive << ( icmp_ln106_fu_402_p2 );
    sensitive << ( icmp_ln107_fu_408_p2 );

    SC_METHOD(thread_icmp_ln109_fu_420_p2);
    sensitive << ( p_read );
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );
    sensitive << ( icmp_ln96_fu_342_p2 );
    sensitive << ( icmp_ln97_fu_348_p2 );
    sensitive << ( icmp_ln98_fu_354_p2 );
    sensitive << ( icmp_ln99_fu_360_p2 );
    sensitive << ( icmp_ln100_fu_366_p2 );
    sensitive << ( icmp_ln101_fu_372_p2 );
    sensitive << ( icmp_ln102_fu_378_p2 );
    sensitive << ( icmp_ln103_fu_384_p2 );
    sensitive << ( icmp_ln104_fu_390_p2 );
    sensitive << ( icmp_ln105_fu_396_p2 );
    sensitive << ( icmp_ln106_fu_402_p2 );
    sensitive << ( icmp_ln107_fu_408_p2 );

    SC_METHOD(thread_icmp_ln94_fu_330_p2);
    sensitive << ( p_read );

    SC_METHOD(thread_icmp_ln95_fu_336_p2);
    sensitive << ( p_read );
    sensitive << ( icmp_ln94_fu_330_p2 );

    SC_METHOD(thread_icmp_ln96_fu_342_p2);
    sensitive << ( p_read );
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );

    SC_METHOD(thread_icmp_ln97_fu_348_p2);
    sensitive << ( p_read );
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );
    sensitive << ( icmp_ln96_fu_342_p2 );

    SC_METHOD(thread_icmp_ln98_fu_354_p2);
    sensitive << ( p_read );
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );
    sensitive << ( icmp_ln96_fu_342_p2 );
    sensitive << ( icmp_ln97_fu_348_p2 );

    SC_METHOD(thread_icmp_ln99_fu_360_p2);
    sensitive << ( p_read );
    sensitive << ( icmp_ln94_fu_330_p2 );
    sensitive << ( icmp_ln95_fu_336_p2 );
    sensitive << ( icmp_ln96_fu_342_p2 );
    sensitive << ( icmp_ln97_fu_348_p2 );
    sensitive << ( icmp_ln98_fu_354_p2 );

    SC_METHOD(thread_or_ln108_fu_426_p2);
    sensitive << ( icmp_ln108_fu_414_p2 );
    sensitive << ( icmp_ln109_fu_420_p2 );

    SC_METHOD(thread_select_ln108_fu_433_p3);
    sensitive << ( icmp_ln108_fu_414_p2 );

    SC_METHOD(thread_select_ln111_1_fu_482_p3);
    sensitive << ( p_read2 );
    sensitive << ( ap_phi_mux_write_flag3_15_phi_fu_85_p30 );
    sensitive << ( zext_ln111_fu_458_p1 );

    SC_METHOD(thread_select_ln111_2_fu_490_p3);
    sensitive << ( p_read3 );
    sensitive << ( ap_phi_mux_write_flag3_15_phi_fu_85_p30 );
    sensitive << ( zext_ln111_2_fu_466_p1 );

    SC_METHOD(thread_select_ln111_3_fu_498_p3);
    sensitive << ( p_read4 );
    sensitive << ( ap_phi_mux_write_flag3_15_phi_fu_85_p30 );
    sensitive << ( zext_ln111_3_fu_470_p1 );

    SC_METHOD(thread_select_ln111_fu_474_p3);
    sensitive << ( p_read1 );
    sensitive << ( ap_phi_mux_write_flag3_15_phi_fu_85_p30 );
    sensitive << ( zext_ln111_1_fu_462_p1 );

    SC_METHOD(thread_sext_ln111_1_fu_446_p1);
    sensitive << ( ap_phi_mux_bin_0_15_phi_fu_184_p30 );

    SC_METHOD(thread_sext_ln111_2_fu_450_p1);
    sensitive << ( ap_phi_mux_bin_2_15_phi_fu_234_p30 );

    SC_METHOD(thread_sext_ln111_3_fu_454_p1);
    sensitive << ( ap_phi_mux_bin_3_15_phi_fu_284_p30 );

    SC_METHOD(thread_sext_ln111_fu_442_p1);
    sensitive << ( ap_phi_mux_bin_1_15_phi_fu_134_p30 );

    SC_METHOD(thread_zext_ln111_1_fu_462_p1);
    sensitive << ( sext_ln111_1_fu_446_p1 );

    SC_METHOD(thread_zext_ln111_2_fu_466_p1);
    sensitive << ( sext_ln111_2_fu_450_p1 );

    SC_METHOD(thread_zext_ln111_3_fu_470_p1);
    sensitive << ( sext_ln111_3_fu_454_p1 );

    SC_METHOD(thread_zext_ln111_fu_458_p1);
    sensitive << ( sext_ln111_fu_442_p1 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "convert_hex_to_binar_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_read, "(port)p_read");
    sc_trace(mVcdFile, p_read1, "(port)p_read1");
    sc_trace(mVcdFile, p_read2, "(port)p_read2");
    sc_trace(mVcdFile, p_read3, "(port)p_read3");
    sc_trace(mVcdFile, p_read4, "(port)p_read4");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_phi_mux_write_flag3_15_phi_fu_85_p30, "ap_phi_mux_write_flag3_15_phi_fu_85_p30");
    sc_trace(mVcdFile, icmp_ln94_fu_330_p2, "icmp_ln94_fu_330_p2");
    sc_trace(mVcdFile, icmp_ln95_fu_336_p2, "icmp_ln95_fu_336_p2");
    sc_trace(mVcdFile, icmp_ln96_fu_342_p2, "icmp_ln96_fu_342_p2");
    sc_trace(mVcdFile, icmp_ln97_fu_348_p2, "icmp_ln97_fu_348_p2");
    sc_trace(mVcdFile, icmp_ln98_fu_354_p2, "icmp_ln98_fu_354_p2");
    sc_trace(mVcdFile, icmp_ln99_fu_360_p2, "icmp_ln99_fu_360_p2");
    sc_trace(mVcdFile, icmp_ln100_fu_366_p2, "icmp_ln100_fu_366_p2");
    sc_trace(mVcdFile, icmp_ln101_fu_372_p2, "icmp_ln101_fu_372_p2");
    sc_trace(mVcdFile, icmp_ln102_fu_378_p2, "icmp_ln102_fu_378_p2");
    sc_trace(mVcdFile, icmp_ln103_fu_384_p2, "icmp_ln103_fu_384_p2");
    sc_trace(mVcdFile, icmp_ln104_fu_390_p2, "icmp_ln104_fu_390_p2");
    sc_trace(mVcdFile, icmp_ln105_fu_396_p2, "icmp_ln105_fu_396_p2");
    sc_trace(mVcdFile, icmp_ln106_fu_402_p2, "icmp_ln106_fu_402_p2");
    sc_trace(mVcdFile, icmp_ln107_fu_408_p2, "icmp_ln107_fu_408_p2");
    sc_trace(mVcdFile, or_ln108_fu_426_p2, "or_ln108_fu_426_p2");
    sc_trace(mVcdFile, ap_phi_mux_bin_1_15_phi_fu_134_p30, "ap_phi_mux_bin_1_15_phi_fu_134_p30");
    sc_trace(mVcdFile, ap_phi_mux_bin_0_15_phi_fu_184_p30, "ap_phi_mux_bin_0_15_phi_fu_184_p30");
    sc_trace(mVcdFile, ap_phi_mux_bin_2_15_phi_fu_234_p30, "ap_phi_mux_bin_2_15_phi_fu_234_p30");
    sc_trace(mVcdFile, ap_phi_mux_bin_3_15_phi_fu_284_p30, "ap_phi_mux_bin_3_15_phi_fu_284_p30");
    sc_trace(mVcdFile, select_ln108_fu_433_p3, "select_ln108_fu_433_p3");
    sc_trace(mVcdFile, icmp_ln108_fu_414_p2, "icmp_ln108_fu_414_p2");
    sc_trace(mVcdFile, icmp_ln109_fu_420_p2, "icmp_ln109_fu_420_p2");
    sc_trace(mVcdFile, sext_ln111_fu_442_p1, "sext_ln111_fu_442_p1");
    sc_trace(mVcdFile, sext_ln111_1_fu_446_p1, "sext_ln111_1_fu_446_p1");
    sc_trace(mVcdFile, sext_ln111_2_fu_450_p1, "sext_ln111_2_fu_450_p1");
    sc_trace(mVcdFile, sext_ln111_3_fu_454_p1, "sext_ln111_3_fu_454_p1");
    sc_trace(mVcdFile, zext_ln111_1_fu_462_p1, "zext_ln111_1_fu_462_p1");
    sc_trace(mVcdFile, zext_ln111_fu_458_p1, "zext_ln111_fu_458_p1");
    sc_trace(mVcdFile, zext_ln111_2_fu_466_p1, "zext_ln111_2_fu_466_p1");
    sc_trace(mVcdFile, zext_ln111_3_fu_470_p1, "zext_ln111_3_fu_470_p1");
    sc_trace(mVcdFile, select_ln111_fu_474_p3, "select_ln111_fu_474_p3");
    sc_trace(mVcdFile, select_ln111_1_fu_482_p3, "select_ln111_1_fu_482_p3");
    sc_trace(mVcdFile, select_ln111_2_fu_490_p3, "select_ln111_2_fu_490_p3");
    sc_trace(mVcdFile, select_ln111_3_fu_498_p3, "select_ln111_3_fu_498_p3");
#endif

    }
}

convert_hex_to_binar_1::~convert_hex_to_binar_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void convert_hex_to_binar_1::thread_ap_phi_mux_bin_0_15_phi_fu_184_p30() {
    if (((esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln102_fu_378_p2.read())) || 
         (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln103_fu_384_p2.read())) || 
         (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln104_fu_390_p2.read())) || 
         (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln105_fu_396_p2.read())) || 
         (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln105_fu_396_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln106_fu_402_p2.read())) || 
         (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln105_fu_396_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln106_fu_402_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln107_fu_408_p2.read())) || 
         (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln105_fu_396_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln106_fu_402_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln107_fu_408_p2.read())))) {
        ap_phi_mux_bin_0_15_phi_fu_184_p30 = ap_const_lv5_11;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln94_fu_330_p2.read()) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln95_fu_336_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln96_fu_342_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln97_fu_348_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln98_fu_354_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln99_fu_360_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln100_fu_366_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln101_fu_372_p2.read())))) {
        ap_phi_mux_bin_0_15_phi_fu_184_p30 = ap_const_lv5_10;
    } else {
        ap_phi_mux_bin_0_15_phi_fu_184_p30 = "XXXXX";
    }
}

void convert_hex_to_binar_1::thread_ap_phi_mux_bin_1_15_phi_fu_134_p30() {
    if (((esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln98_fu_354_p2.read())) || 
         (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln99_fu_360_p2.read())) || 
         (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln100_fu_366_p2.read())) || 
         (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln101_fu_372_p2.read())) || 
         (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln105_fu_396_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln106_fu_402_p2.read())) || 
         (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln105_fu_396_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln106_fu_402_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln107_fu_408_p2.read())) || 
         (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln105_fu_396_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln106_fu_402_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln107_fu_408_p2.read())))) {
        ap_phi_mux_bin_1_15_phi_fu_134_p30 = ap_const_lv5_11;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln94_fu_330_p2.read()) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln95_fu_336_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln96_fu_342_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln97_fu_348_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln102_fu_378_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln103_fu_384_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln104_fu_390_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln105_fu_396_p2.read())))) {
        ap_phi_mux_bin_1_15_phi_fu_134_p30 = ap_const_lv5_10;
    } else {
        ap_phi_mux_bin_1_15_phi_fu_134_p30 = "XXXXX";
    }
}

void convert_hex_to_binar_1::thread_ap_phi_mux_bin_2_15_phi_fu_234_p30() {
    if (((esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln96_fu_342_p2.read())) || 
         (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln97_fu_348_p2.read())) || 
         (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln100_fu_366_p2.read())) || 
         (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln101_fu_372_p2.read())) || 
         (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln104_fu_390_p2.read())) || 
         (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln105_fu_396_p2.read())) || 
         (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln105_fu_396_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln106_fu_402_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln107_fu_408_p2.read())))) {
        ap_phi_mux_bin_2_15_phi_fu_234_p30 = ap_const_lv5_11;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln94_fu_330_p2.read()) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln95_fu_336_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln98_fu_354_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln99_fu_360_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln102_fu_378_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln103_fu_384_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln105_fu_396_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln106_fu_402_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln105_fu_396_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln106_fu_402_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln107_fu_408_p2.read())))) {
        ap_phi_mux_bin_2_15_phi_fu_234_p30 = ap_const_lv5_10;
    } else {
        ap_phi_mux_bin_2_15_phi_fu_234_p30 = "XXXXX";
    }
}

void convert_hex_to_binar_1::thread_ap_phi_mux_bin_3_15_phi_fu_284_p30() {
    if ((esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln105_fu_396_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln106_fu_402_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln107_fu_408_p2.read()))) {
        ap_phi_mux_bin_3_15_phi_fu_284_p30 = select_ln108_fu_433_p3.read();
    } else if (((esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln95_fu_336_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln97_fu_348_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln99_fu_360_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln101_fu_372_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln103_fu_384_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln105_fu_396_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln105_fu_396_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln106_fu_402_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln107_fu_408_p2.read())))) {
        ap_phi_mux_bin_3_15_phi_fu_284_p30 = ap_const_lv5_11;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln94_fu_330_p2.read()) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln96_fu_342_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln98_fu_354_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln100_fu_366_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln102_fu_378_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln104_fu_390_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln105_fu_396_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln106_fu_402_p2.read())))) {
        ap_phi_mux_bin_3_15_phi_fu_284_p30 = ap_const_lv5_10;
    } else {
        ap_phi_mux_bin_3_15_phi_fu_284_p30 = "XXXXX";
    }
}

void convert_hex_to_binar_1::thread_ap_phi_mux_write_flag3_15_phi_fu_85_p30() {
    if ((esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln105_fu_396_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln106_fu_402_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln107_fu_408_p2.read()))) {
        ap_phi_mux_write_flag3_15_phi_fu_85_p30 = or_ln108_fu_426_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln94_fu_330_p2.read()) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln95_fu_336_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln96_fu_342_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln97_fu_348_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln98_fu_354_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln99_fu_360_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln100_fu_366_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln101_fu_372_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln102_fu_378_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln103_fu_384_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln104_fu_390_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln105_fu_396_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln105_fu_396_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln106_fu_402_p2.read())) || 
                (esl_seteq<1,1,1>(icmp_ln94_fu_330_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_336_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_342_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_348_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_354_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_360_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_366_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_372_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_378_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln103_fu_384_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_390_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln105_fu_396_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln106_fu_402_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln107_fu_408_p2.read())))) {
        ap_phi_mux_write_flag3_15_phi_fu_85_p30 = ap_const_lv1_1;
    } else {
        ap_phi_mux_write_flag3_15_phi_fu_85_p30 =  (sc_lv<1>) ("X");
    }
}

void convert_hex_to_binar_1::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void convert_hex_to_binar_1::thread_ap_return_0() {
    ap_return_0 = select_ln111_fu_474_p3.read();
}

void convert_hex_to_binar_1::thread_ap_return_1() {
    ap_return_1 = select_ln111_1_fu_482_p3.read();
}

void convert_hex_to_binar_1::thread_ap_return_2() {
    ap_return_2 = select_ln111_2_fu_490_p3.read();
}

void convert_hex_to_binar_1::thread_ap_return_3() {
    ap_return_3 = select_ln111_3_fu_498_p3.read();
}

void convert_hex_to_binar_1::thread_icmp_ln100_fu_366_p2() {
    icmp_ln100_fu_366_p2 = (!p_read.read().is_01() || !ap_const_lv8_36.is_01())? sc_lv<1>(): sc_lv<1>(p_read.read() == ap_const_lv8_36);
}

void convert_hex_to_binar_1::thread_icmp_ln101_fu_372_p2() {
    icmp_ln101_fu_372_p2 = (!p_read.read().is_01() || !ap_const_lv8_37.is_01())? sc_lv<1>(): sc_lv<1>(p_read.read() == ap_const_lv8_37);
}

void convert_hex_to_binar_1::thread_icmp_ln102_fu_378_p2() {
    icmp_ln102_fu_378_p2 = (!p_read.read().is_01() || !ap_const_lv8_38.is_01())? sc_lv<1>(): sc_lv<1>(p_read.read() == ap_const_lv8_38);
}

void convert_hex_to_binar_1::thread_icmp_ln103_fu_384_p2() {
    icmp_ln103_fu_384_p2 = (!p_read.read().is_01() || !ap_const_lv8_39.is_01())? sc_lv<1>(): sc_lv<1>(p_read.read() == ap_const_lv8_39);
}

void convert_hex_to_binar_1::thread_icmp_ln104_fu_390_p2() {
    icmp_ln104_fu_390_p2 = (!p_read.read().is_01() || !ap_const_lv8_61.is_01())? sc_lv<1>(): sc_lv<1>(p_read.read() == ap_const_lv8_61);
}

void convert_hex_to_binar_1::thread_icmp_ln105_fu_396_p2() {
    icmp_ln105_fu_396_p2 = (!p_read.read().is_01() || !ap_const_lv8_62.is_01())? sc_lv<1>(): sc_lv<1>(p_read.read() == ap_const_lv8_62);
}

void convert_hex_to_binar_1::thread_icmp_ln106_fu_402_p2() {
    icmp_ln106_fu_402_p2 = (!p_read.read().is_01() || !ap_const_lv8_63.is_01())? sc_lv<1>(): sc_lv<1>(p_read.read() == ap_const_lv8_63);
}

void convert_hex_to_binar_1::thread_icmp_ln107_fu_408_p2() {
    icmp_ln107_fu_408_p2 = (!p_read.read().is_01() || !ap_const_lv8_64.is_01())? sc_lv<1>(): sc_lv<1>(p_read.read() == ap_const_lv8_64);
}

void convert_hex_to_binar_1::thread_icmp_ln108_fu_414_p2() {
    icmp_ln108_fu_414_p2 = (!p_read.read().is_01() || !ap_const_lv8_65.is_01())? sc_lv<1>(): sc_lv<1>(p_read.read() == ap_const_lv8_65);
}

void convert_hex_to_binar_1::thread_icmp_ln109_fu_420_p2() {
    icmp_ln109_fu_420_p2 = (!p_read.read().is_01() || !ap_const_lv8_66.is_01())? sc_lv<1>(): sc_lv<1>(p_read.read() == ap_const_lv8_66);
}

void convert_hex_to_binar_1::thread_icmp_ln94_fu_330_p2() {
    icmp_ln94_fu_330_p2 = (!p_read.read().is_01() || !ap_const_lv8_30.is_01())? sc_lv<1>(): sc_lv<1>(p_read.read() == ap_const_lv8_30);
}

void convert_hex_to_binar_1::thread_icmp_ln95_fu_336_p2() {
    icmp_ln95_fu_336_p2 = (!p_read.read().is_01() || !ap_const_lv8_31.is_01())? sc_lv<1>(): sc_lv<1>(p_read.read() == ap_const_lv8_31);
}

void convert_hex_to_binar_1::thread_icmp_ln96_fu_342_p2() {
    icmp_ln96_fu_342_p2 = (!p_read.read().is_01() || !ap_const_lv8_32.is_01())? sc_lv<1>(): sc_lv<1>(p_read.read() == ap_const_lv8_32);
}

void convert_hex_to_binar_1::thread_icmp_ln97_fu_348_p2() {
    icmp_ln97_fu_348_p2 = (!p_read.read().is_01() || !ap_const_lv8_33.is_01())? sc_lv<1>(): sc_lv<1>(p_read.read() == ap_const_lv8_33);
}

void convert_hex_to_binar_1::thread_icmp_ln98_fu_354_p2() {
    icmp_ln98_fu_354_p2 = (!p_read.read().is_01() || !ap_const_lv8_34.is_01())? sc_lv<1>(): sc_lv<1>(p_read.read() == ap_const_lv8_34);
}

void convert_hex_to_binar_1::thread_icmp_ln99_fu_360_p2() {
    icmp_ln99_fu_360_p2 = (!p_read.read().is_01() || !ap_const_lv8_35.is_01())? sc_lv<1>(): sc_lv<1>(p_read.read() == ap_const_lv8_35);
}

void convert_hex_to_binar_1::thread_or_ln108_fu_426_p2() {
    or_ln108_fu_426_p2 = (icmp_ln108_fu_414_p2.read() | icmp_ln109_fu_420_p2.read());
}

void convert_hex_to_binar_1::thread_select_ln108_fu_433_p3() {
    select_ln108_fu_433_p3 = (!icmp_ln108_fu_414_p2.read()[0].is_01())? sc_lv<5>(): ((icmp_ln108_fu_414_p2.read()[0].to_bool())? ap_const_lv5_10: ap_const_lv5_11);
}

void convert_hex_to_binar_1::thread_select_ln111_1_fu_482_p3() {
    select_ln111_1_fu_482_p3 = (!ap_phi_mux_write_flag3_15_phi_fu_85_p30.read()[0].is_01())? sc_lv<8>(): ((ap_phi_mux_write_flag3_15_phi_fu_85_p30.read()[0].to_bool())? zext_ln111_fu_458_p1.read(): p_read2.read());
}

void convert_hex_to_binar_1::thread_select_ln111_2_fu_490_p3() {
    select_ln111_2_fu_490_p3 = (!ap_phi_mux_write_flag3_15_phi_fu_85_p30.read()[0].is_01())? sc_lv<8>(): ((ap_phi_mux_write_flag3_15_phi_fu_85_p30.read()[0].to_bool())? zext_ln111_2_fu_466_p1.read(): p_read3.read());
}

void convert_hex_to_binar_1::thread_select_ln111_3_fu_498_p3() {
    select_ln111_3_fu_498_p3 = (!ap_phi_mux_write_flag3_15_phi_fu_85_p30.read()[0].is_01())? sc_lv<8>(): ((ap_phi_mux_write_flag3_15_phi_fu_85_p30.read()[0].to_bool())? zext_ln111_3_fu_470_p1.read(): p_read4.read());
}

void convert_hex_to_binar_1::thread_select_ln111_fu_474_p3() {
    select_ln111_fu_474_p3 = (!ap_phi_mux_write_flag3_15_phi_fu_85_p30.read()[0].is_01())? sc_lv<8>(): ((ap_phi_mux_write_flag3_15_phi_fu_85_p30.read()[0].to_bool())? zext_ln111_1_fu_462_p1.read(): p_read1.read());
}

void convert_hex_to_binar_1::thread_sext_ln111_1_fu_446_p1() {
    sext_ln111_1_fu_446_p1 = esl_sext<6,5>(ap_phi_mux_bin_0_15_phi_fu_184_p30.read());
}

void convert_hex_to_binar_1::thread_sext_ln111_2_fu_450_p1() {
    sext_ln111_2_fu_450_p1 = esl_sext<6,5>(ap_phi_mux_bin_2_15_phi_fu_234_p30.read());
}

void convert_hex_to_binar_1::thread_sext_ln111_3_fu_454_p1() {
    sext_ln111_3_fu_454_p1 = esl_sext<6,5>(ap_phi_mux_bin_3_15_phi_fu_284_p30.read());
}

void convert_hex_to_binar_1::thread_sext_ln111_fu_442_p1() {
    sext_ln111_fu_442_p1 = esl_sext<6,5>(ap_phi_mux_bin_1_15_phi_fu_134_p30.read());
}

void convert_hex_to_binar_1::thread_zext_ln111_1_fu_462_p1() {
    zext_ln111_1_fu_462_p1 = esl_zext<8,6>(sext_ln111_1_fu_446_p1.read());
}

void convert_hex_to_binar_1::thread_zext_ln111_2_fu_466_p1() {
    zext_ln111_2_fu_466_p1 = esl_zext<8,6>(sext_ln111_2_fu_450_p1.read());
}

void convert_hex_to_binar_1::thread_zext_ln111_3_fu_470_p1() {
    zext_ln111_3_fu_470_p1 = esl_zext<8,6>(sext_ln111_3_fu_454_p1.read());
}

void convert_hex_to_binar_1::thread_zext_ln111_fu_458_p1() {
    zext_ln111_fu_458_p1 = esl_zext<8,6>(sext_ln111_fu_442_p1.read());
}

}

