// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "split_2_hw.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic split_2_hw::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic split_2_hw::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> split_2_hw::ap_ST_fsm_state1 = "1";
const sc_lv<3> split_2_hw::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> split_2_hw::ap_ST_fsm_state5 = "100";
const bool split_2_hw::ap_const_boolean_1 = true;
const sc_lv<32> split_2_hw::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> split_2_hw::ap_const_lv32_1 = "1";
const bool split_2_hw::ap_const_boolean_0 = false;
const sc_lv<1> split_2_hw::ap_const_lv1_0 = "0";
const sc_lv<1> split_2_hw::ap_const_lv1_1 = "1";
const sc_lv<7> split_2_hw::ap_const_lv7_0 = "0000000";
const sc_lv<3> split_2_hw::ap_const_lv3_0 = "000";
const sc_lv<6> split_2_hw::ap_const_lv6_0 = "000000";
const sc_lv<8> split_2_hw::ap_const_lv8_2 = "10";
const sc_lv<4> split_2_hw::ap_const_lv4_6 = "110";
const sc_lv<7> split_2_hw::ap_const_lv7_40 = "1000000";
const sc_lv<7> split_2_hw::ap_const_lv7_1 = "1";
const sc_lv<3> split_2_hw::ap_const_lv3_1 = "1";
const sc_lv<6> split_2_hw::ap_const_lv6_10 = "10000";
const sc_lv<32> split_2_hw::ap_const_lv32_3 = "11";
const sc_lv<8> split_2_hw::ap_const_lv8_6E = "1101110";
const sc_lv<4> split_2_hw::ap_const_lv4_E = "1110";
const sc_lv<6> split_2_hw::ap_const_lv6_1 = "1";
const sc_lv<2> split_2_hw::ap_const_lv2_0 = "00";
const sc_lv<11> split_2_hw::ap_const_lv11_1 = "1";
const sc_lv<11> split_2_hw::ap_const_lv11_2 = "10";
const sc_lv<32> split_2_hw::ap_const_lv32_2 = "10";

split_2_hw::split_2_hw(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln54_fu_228_p2);
    sensitive << ( indvar_flatten17_reg_142 );

    SC_METHOD(thread_add_ln55_1_fu_329_p2);
    sensitive << ( indvar_flatten_reg_164 );

    SC_METHOD(thread_add_ln56_fu_343_p2);
    sensitive << ( count2_reg_196 );

    SC_METHOD(thread_add_ln59_1_fu_381_p2);
    sensitive << ( p_shl_cast_fu_373_p3 );
    sensitive << ( zext_ln59_2_fu_369_p1 );

    SC_METHOD(thread_add_ln59_2_fu_393_p2);
    sensitive << ( sext_ln59_fu_390_p1 );
    sensitive << ( add_ln59_1_fu_381_p2 );

    SC_METHOD(thread_add_ln59_fu_363_p2);
    sensitive << ( zext_ln59_1_fu_360_p1 );
    sensitive << ( zext_ln59_fu_356_p1 );

    SC_METHOD(thread_add_ln60_1_fu_414_p2);
    sensitive << ( add_ln59_1_fu_381_p2 );
    sensitive << ( zext_ln60_fu_410_p1 );

    SC_METHOD(thread_add_ln60_fu_430_p2);
    sensitive << ( count1_2_reg_186 );

    SC_METHOD(thread_and_ln62_fu_318_p2);
    sensitive << ( mode );
    sensitive << ( icmp_ln62_fu_312_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_phi_mux_i_0_phi_fu_157_p4);
    sensitive << ( i_0_reg_153 );
    sensitive << ( icmp_ln54_reg_457 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( select_ln59_2_reg_466 );
    sensitive << ( and_ln62_reg_484 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_j_0_phi_fu_179_p4);
    sensitive << ( j_0_reg_175 );
    sensitive << ( icmp_ln54_reg_457 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( select_ln59_4_reg_478 );
    sensitive << ( and_ln62_reg_484 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_predicate_tran4to5_state2);
    sensitive << ( icmp_ln54_fu_222_p2 );
    sensitive << ( and_ln62_fu_318_p2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_count1_fu_441_p2);
    sensitive << ( count1_2_reg_186 );

    SC_METHOD(thread_empty_fu_218_p1);
    sensitive << ( start );

    SC_METHOD(thread_i_fu_234_p2);
    sensitive << ( ap_phi_mux_i_0_phi_fu_157_p4 );

    SC_METHOD(thread_icmp_ln54_fu_222_p2);
    sensitive << ( indvar_flatten17_reg_142 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln55_fu_240_p2);
    sensitive << ( indvar_flatten_reg_164 );
    sensitive << ( icmp_ln54_fu_222_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln62_fu_312_p2);
    sensitive << ( count2_reg_196 );
    sensitive << ( icmp_ln54_fu_222_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_j_fu_290_p2);
    sensitive << ( select_ln59_fu_246_p3 );

    SC_METHOD(thread_k_fu_323_p2);
    sensitive << ( select_ln59_3_fu_296_p3 );

    SC_METHOD(thread_key_stream_address0);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln59_4_fu_425_p1 );

    SC_METHOD(thread_key_stream_address1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln60_1_fu_436_p1 );

    SC_METHOD(thread_key_stream_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_key_stream_ce1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_key_stream_d0);
    sensitive << ( state_matrix_q0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_key_stream_d1);
    sensitive << ( state_matrix_q1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_key_stream_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln54_reg_457_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_key_stream_we1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln54_reg_457_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_or_ln59_fu_284_p2);
    sensitive << ( icmp_ln55_fu_240_p2 );
    sensitive << ( xor_ln56_fu_278_p2 );

    SC_METHOD(thread_or_ln60_fu_404_p2);
    sensitive << ( trunc_ln56_fu_387_p1 );

    SC_METHOD(thread_p_shl_cast_fu_373_p3);
    sensitive << ( add_ln59_fu_363_p2 );

    SC_METHOD(thread_select_ln55_fu_335_p3);
    sensitive << ( icmp_ln55_fu_240_p2 );
    sensitive << ( add_ln55_1_fu_329_p2 );

    SC_METHOD(thread_select_ln59_1_fu_254_p3);
    sensitive << ( k_0_reg_207 );
    sensitive << ( icmp_ln55_fu_240_p2 );

    SC_METHOD(thread_select_ln59_2_fu_262_p3);
    sensitive << ( ap_phi_mux_i_0_phi_fu_157_p4 );
    sensitive << ( icmp_ln55_fu_240_p2 );
    sensitive << ( i_fu_234_p2 );

    SC_METHOD(thread_select_ln59_3_fu_296_p3);
    sensitive << ( or_ln59_fu_284_p2 );
    sensitive << ( select_ln59_1_fu_254_p3 );

    SC_METHOD(thread_select_ln59_4_fu_304_p3);
    sensitive << ( select_ln59_fu_246_p3 );
    sensitive << ( or_ln59_fu_284_p2 );
    sensitive << ( j_fu_290_p2 );

    SC_METHOD(thread_select_ln59_fu_246_p3);
    sensitive << ( ap_phi_mux_j_0_phi_fu_179_p4 );
    sensitive << ( icmp_ln55_fu_240_p2 );

    SC_METHOD(thread_sext_ln59_fu_390_p1);
    sensitive << ( select_ln59_3_reg_472 );

    SC_METHOD(thread_state_matrix_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln59_3_fu_399_p1 );

    SC_METHOD(thread_state_matrix_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln60_2_fu_420_p1 );

    SC_METHOD(thread_state_matrix_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_state_matrix_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_tmp_1_fu_270_p3);
    sensitive << ( k_0_reg_207 );

    SC_METHOD(thread_tmp_s_fu_349_p3);
    sensitive << ( select_ln59_2_reg_466 );

    SC_METHOD(thread_trunc_ln56_fu_387_p1);
    sensitive << ( select_ln59_3_reg_472 );

    SC_METHOD(thread_xor_ln56_fu_278_p2);
    sensitive << ( tmp_1_fu_270_p3 );

    SC_METHOD(thread_zext_ln59_1_fu_360_p1);
    sensitive << ( select_ln59_4_reg_478 );

    SC_METHOD(thread_zext_ln59_2_fu_369_p1);
    sensitive << ( add_ln59_fu_363_p2 );

    SC_METHOD(thread_zext_ln59_3_fu_399_p1);
    sensitive << ( add_ln59_2_fu_393_p2 );

    SC_METHOD(thread_zext_ln59_4_fu_425_p1);
    sensitive << ( count1_2_reg_186 );

    SC_METHOD(thread_zext_ln59_fu_356_p1);
    sensitive << ( tmp_s_fu_349_p3 );

    SC_METHOD(thread_zext_ln60_1_fu_436_p1);
    sensitive << ( add_ln60_fu_430_p2 );

    SC_METHOD(thread_zext_ln60_2_fu_420_p1);
    sensitive << ( add_ln60_1_fu_414_p2 );

    SC_METHOD(thread_zext_ln60_fu_410_p1);
    sensitive << ( or_ln60_fu_404_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "split_2_hw_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, state_matrix_address0, "(port)state_matrix_address0");
    sc_trace(mVcdFile, state_matrix_ce0, "(port)state_matrix_ce0");
    sc_trace(mVcdFile, state_matrix_q0, "(port)state_matrix_q0");
    sc_trace(mVcdFile, state_matrix_address1, "(port)state_matrix_address1");
    sc_trace(mVcdFile, state_matrix_ce1, "(port)state_matrix_ce1");
    sc_trace(mVcdFile, state_matrix_q1, "(port)state_matrix_q1");
    sc_trace(mVcdFile, key_stream_address0, "(port)key_stream_address0");
    sc_trace(mVcdFile, key_stream_ce0, "(port)key_stream_ce0");
    sc_trace(mVcdFile, key_stream_we0, "(port)key_stream_we0");
    sc_trace(mVcdFile, key_stream_d0, "(port)key_stream_d0");
    sc_trace(mVcdFile, key_stream_address1, "(port)key_stream_address1");
    sc_trace(mVcdFile, key_stream_ce1, "(port)key_stream_ce1");
    sc_trace(mVcdFile, key_stream_we1, "(port)key_stream_we1");
    sc_trace(mVcdFile, key_stream_d1, "(port)key_stream_d1");
    sc_trace(mVcdFile, start, "(port)start");
    sc_trace(mVcdFile, mode, "(port)mode");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvar_flatten17_reg_142, "indvar_flatten17_reg_142");
    sc_trace(mVcdFile, i_0_reg_153, "i_0_reg_153");
    sc_trace(mVcdFile, indvar_flatten_reg_164, "indvar_flatten_reg_164");
    sc_trace(mVcdFile, j_0_reg_175, "j_0_reg_175");
    sc_trace(mVcdFile, count1_2_reg_186, "count1_2_reg_186");
    sc_trace(mVcdFile, count2_reg_196, "count2_reg_196");
    sc_trace(mVcdFile, k_0_reg_207, "k_0_reg_207");
    sc_trace(mVcdFile, empty_fu_218_p1, "empty_fu_218_p1");
    sc_trace(mVcdFile, icmp_ln54_fu_222_p2, "icmp_ln54_fu_222_p2");
    sc_trace(mVcdFile, icmp_ln54_reg_457, "icmp_ln54_reg_457");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln54_reg_457_pp0_iter1_reg, "icmp_ln54_reg_457_pp0_iter1_reg");
    sc_trace(mVcdFile, add_ln54_fu_228_p2, "add_ln54_fu_228_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, select_ln59_2_fu_262_p3, "select_ln59_2_fu_262_p3");
    sc_trace(mVcdFile, select_ln59_2_reg_466, "select_ln59_2_reg_466");
    sc_trace(mVcdFile, select_ln59_3_fu_296_p3, "select_ln59_3_fu_296_p3");
    sc_trace(mVcdFile, select_ln59_3_reg_472, "select_ln59_3_reg_472");
    sc_trace(mVcdFile, select_ln59_4_fu_304_p3, "select_ln59_4_fu_304_p3");
    sc_trace(mVcdFile, select_ln59_4_reg_478, "select_ln59_4_reg_478");
    sc_trace(mVcdFile, and_ln62_fu_318_p2, "and_ln62_fu_318_p2");
    sc_trace(mVcdFile, and_ln62_reg_484, "and_ln62_reg_484");
    sc_trace(mVcdFile, and_ln62_reg_484_pp0_iter1_reg, "and_ln62_reg_484_pp0_iter1_reg");
    sc_trace(mVcdFile, k_fu_323_p2, "k_fu_323_p2");
    sc_trace(mVcdFile, select_ln55_fu_335_p3, "select_ln55_fu_335_p3");
    sc_trace(mVcdFile, add_ln56_fu_343_p2, "add_ln56_fu_343_p2");
    sc_trace(mVcdFile, count1_fu_441_p2, "count1_fu_441_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_predicate_tran4to5_state2, "ap_predicate_tran4to5_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_phi_mux_i_0_phi_fu_157_p4, "ap_phi_mux_i_0_phi_fu_157_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_phi_mux_j_0_phi_fu_179_p4, "ap_phi_mux_j_0_phi_fu_179_p4");
    sc_trace(mVcdFile, zext_ln59_3_fu_399_p1, "zext_ln59_3_fu_399_p1");
    sc_trace(mVcdFile, zext_ln60_2_fu_420_p1, "zext_ln60_2_fu_420_p1");
    sc_trace(mVcdFile, zext_ln59_4_fu_425_p1, "zext_ln59_4_fu_425_p1");
    sc_trace(mVcdFile, zext_ln60_1_fu_436_p1, "zext_ln60_1_fu_436_p1");
    sc_trace(mVcdFile, icmp_ln55_fu_240_p2, "icmp_ln55_fu_240_p2");
    sc_trace(mVcdFile, i_fu_234_p2, "i_fu_234_p2");
    sc_trace(mVcdFile, tmp_1_fu_270_p3, "tmp_1_fu_270_p3");
    sc_trace(mVcdFile, xor_ln56_fu_278_p2, "xor_ln56_fu_278_p2");
    sc_trace(mVcdFile, select_ln59_fu_246_p3, "select_ln59_fu_246_p3");
    sc_trace(mVcdFile, or_ln59_fu_284_p2, "or_ln59_fu_284_p2");
    sc_trace(mVcdFile, select_ln59_1_fu_254_p3, "select_ln59_1_fu_254_p3");
    sc_trace(mVcdFile, j_fu_290_p2, "j_fu_290_p2");
    sc_trace(mVcdFile, icmp_ln62_fu_312_p2, "icmp_ln62_fu_312_p2");
    sc_trace(mVcdFile, add_ln55_1_fu_329_p2, "add_ln55_1_fu_329_p2");
    sc_trace(mVcdFile, tmp_s_fu_349_p3, "tmp_s_fu_349_p3");
    sc_trace(mVcdFile, zext_ln59_1_fu_360_p1, "zext_ln59_1_fu_360_p1");
    sc_trace(mVcdFile, zext_ln59_fu_356_p1, "zext_ln59_fu_356_p1");
    sc_trace(mVcdFile, add_ln59_fu_363_p2, "add_ln59_fu_363_p2");
    sc_trace(mVcdFile, p_shl_cast_fu_373_p3, "p_shl_cast_fu_373_p3");
    sc_trace(mVcdFile, zext_ln59_2_fu_369_p1, "zext_ln59_2_fu_369_p1");
    sc_trace(mVcdFile, sext_ln59_fu_390_p1, "sext_ln59_fu_390_p1");
    sc_trace(mVcdFile, add_ln59_1_fu_381_p2, "add_ln59_1_fu_381_p2");
    sc_trace(mVcdFile, add_ln59_2_fu_393_p2, "add_ln59_2_fu_393_p2");
    sc_trace(mVcdFile, trunc_ln56_fu_387_p1, "trunc_ln56_fu_387_p1");
    sc_trace(mVcdFile, or_ln60_fu_404_p2, "or_ln60_fu_404_p2");
    sc_trace(mVcdFile, zext_ln60_fu_410_p1, "zext_ln60_fu_410_p1");
    sc_trace(mVcdFile, add_ln60_1_fu_414_p2, "add_ln60_1_fu_414_p2");
    sc_trace(mVcdFile, add_ln60_fu_430_p2, "add_ln60_fu_430_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

split_2_hw::~split_2_hw() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void split_2_hw::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_tran4to5_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(icmp_ln54_reg_457_pp0_iter1_reg.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, and_ln62_reg_484_pp0_iter1_reg.read()))) {
        count1_2_reg_186 = count1_fu_441_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        count1_2_reg_186 = empty_fu_218_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln54_fu_222_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, and_ln62_fu_318_p2.read()))) {
        count2_reg_196 = add_ln56_fu_343_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        count2_reg_196 = ap_const_lv8_2;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln54_reg_457.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, and_ln62_reg_484.read()))) {
        i_0_reg_153 = select_ln59_2_reg_466.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_153 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln54_fu_222_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, and_ln62_fu_318_p2.read()))) {
        indvar_flatten17_reg_142 = add_ln54_fu_228_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten17_reg_142 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln54_fu_222_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, and_ln62_fu_318_p2.read()))) {
        indvar_flatten_reg_164 = select_ln55_fu_335_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten_reg_164 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln54_reg_457.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, and_ln62_reg_484.read()))) {
        j_0_reg_175 = select_ln59_4_reg_478.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        j_0_reg_175 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln54_fu_222_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, and_ln62_fu_318_p2.read()))) {
        k_0_reg_207 = k_fu_323_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        k_0_reg_207 = ap_const_lv4_6;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln54_fu_222_p2.read(), ap_const_lv1_0))) {
        and_ln62_reg_484 = and_ln62_fu_318_p2.read();
        select_ln59_3_reg_472 = select_ln59_3_fu_296_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        and_ln62_reg_484_pp0_iter1_reg = and_ln62_reg_484.read();
        icmp_ln54_reg_457 = icmp_ln54_fu_222_p2.read();
        icmp_ln54_reg_457_pp0_iter1_reg = icmp_ln54_reg_457.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(icmp_ln54_fu_222_p2.read(), ap_const_lv1_0))) {
        select_ln59_2_reg_466 = select_ln59_2_fu_262_p3.read();
        select_ln59_4_reg_478 = select_ln59_4_fu_304_p3.read();
    }
}

void split_2_hw::thread_add_ln54_fu_228_p2() {
    add_ln54_fu_228_p2 = (!indvar_flatten17_reg_142.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(indvar_flatten17_reg_142.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void split_2_hw::thread_add_ln55_1_fu_329_p2() {
    add_ln55_1_fu_329_p2 = (!indvar_flatten_reg_164.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(indvar_flatten_reg_164.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void split_2_hw::thread_add_ln56_fu_343_p2() {
    add_ln56_fu_343_p2 = (!count2_reg_196.read().is_01() || !ap_const_lv8_2.is_01())? sc_lv<8>(): (sc_biguint<8>(count2_reg_196.read()) + sc_biguint<8>(ap_const_lv8_2));
}

void split_2_hw::thread_add_ln59_1_fu_381_p2() {
    add_ln59_1_fu_381_p2 = (!p_shl_cast_fu_373_p3.read().is_01() || !zext_ln59_2_fu_369_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(p_shl_cast_fu_373_p3.read()) + sc_biguint<9>(zext_ln59_2_fu_369_p1.read()));
}

void split_2_hw::thread_add_ln59_2_fu_393_p2() {
    add_ln59_2_fu_393_p2 = (!sext_ln59_fu_390_p1.read().is_01() || !add_ln59_1_fu_381_p2.read().is_01())? sc_lv<9>(): (sc_bigint<9>(sext_ln59_fu_390_p1.read()) + sc_biguint<9>(add_ln59_1_fu_381_p2.read()));
}

void split_2_hw::thread_add_ln59_fu_363_p2() {
    add_ln59_fu_363_p2 = (!zext_ln59_1_fu_360_p1.read().is_01() || !zext_ln59_fu_356_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(zext_ln59_1_fu_360_p1.read()) + sc_biguint<6>(zext_ln59_fu_356_p1.read()));
}

void split_2_hw::thread_add_ln60_1_fu_414_p2() {
    add_ln60_1_fu_414_p2 = (!zext_ln60_fu_410_p1.read().is_01() || !add_ln59_1_fu_381_p2.read().is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln60_fu_410_p1.read()) + sc_biguint<9>(add_ln59_1_fu_381_p2.read()));
}

void split_2_hw::thread_add_ln60_fu_430_p2() {
    add_ln60_fu_430_p2 = (!ap_const_lv11_1.is_01() || !count1_2_reg_186.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_1) + sc_biguint<11>(count1_2_reg_186.read()));
}

void split_2_hw::thread_and_ln62_fu_318_p2() {
    and_ln62_fu_318_p2 = (icmp_ln62_fu_312_p2.read() & mode.read());
}

void split_2_hw::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void split_2_hw::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void split_2_hw::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[2];
}

void split_2_hw::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void split_2_hw::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void split_2_hw::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void split_2_hw::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void split_2_hw::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void split_2_hw::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void split_2_hw::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void split_2_hw::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void split_2_hw::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void split_2_hw::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void split_2_hw::thread_ap_phi_mux_i_0_phi_fu_157_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln54_reg_457.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, and_ln62_reg_484.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_i_0_phi_fu_157_p4 = select_ln59_2_reg_466.read();
    } else {
        ap_phi_mux_i_0_phi_fu_157_p4 = i_0_reg_153.read();
    }
}

void split_2_hw::thread_ap_phi_mux_j_0_phi_fu_179_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln54_reg_457.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, and_ln62_reg_484.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_j_0_phi_fu_179_p4 = select_ln59_4_reg_478.read();
    } else {
        ap_phi_mux_j_0_phi_fu_179_p4 = j_0_reg_175.read();
    }
}

void split_2_hw::thread_ap_predicate_tran4to5_state2() {
    ap_predicate_tran4to5_state2 = (esl_seteq<1,1,1>(and_ln62_fu_318_p2.read(), ap_const_lv1_1) || esl_seteq<1,1,1>(icmp_ln54_fu_222_p2.read(), ap_const_lv1_1));
}

void split_2_hw::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void split_2_hw::thread_count1_fu_441_p2() {
    count1_fu_441_p2 = (!ap_const_lv11_2.is_01() || !count1_2_reg_186.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_2) + sc_biguint<11>(count1_2_reg_186.read()));
}

void split_2_hw::thread_empty_fu_218_p1() {
    empty_fu_218_p1 = start.read().range(11-1, 0);
}

void split_2_hw::thread_i_fu_234_p2() {
    i_fu_234_p2 = (!ap_const_lv3_1.is_01() || !ap_phi_mux_i_0_phi_fu_157_p4.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_1) + sc_biguint<3>(ap_phi_mux_i_0_phi_fu_157_p4.read()));
}

void split_2_hw::thread_icmp_ln54_fu_222_p2() {
    icmp_ln54_fu_222_p2 = (!indvar_flatten17_reg_142.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten17_reg_142.read() == ap_const_lv7_40);
}

void split_2_hw::thread_icmp_ln55_fu_240_p2() {
    icmp_ln55_fu_240_p2 = (!indvar_flatten_reg_164.read().is_01() || !ap_const_lv6_10.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_164.read() == ap_const_lv6_10);
}

void split_2_hw::thread_icmp_ln62_fu_312_p2() {
    icmp_ln62_fu_312_p2 = (!count2_reg_196.read().is_01() || !ap_const_lv8_6E.is_01())? sc_lv<1>(): sc_lv<1>(count2_reg_196.read() == ap_const_lv8_6E);
}

void split_2_hw::thread_j_fu_290_p2() {
    j_fu_290_p2 = (!ap_const_lv3_1.is_01() || !select_ln59_fu_246_p3.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_1) + sc_biguint<3>(select_ln59_fu_246_p3.read()));
}

void split_2_hw::thread_k_fu_323_p2() {
    k_fu_323_p2 = (!select_ln59_3_fu_296_p3.read().is_01() || !ap_const_lv4_E.is_01())? sc_lv<4>(): (sc_bigint<4>(select_ln59_3_fu_296_p3.read()) + sc_bigint<4>(ap_const_lv4_E));
}

void split_2_hw::thread_key_stream_address0() {
    key_stream_address0 =  (sc_lv<10>) (zext_ln59_4_fu_425_p1.read());
}

void split_2_hw::thread_key_stream_address1() {
    key_stream_address1 =  (sc_lv<10>) (zext_ln60_1_fu_436_p1.read());
}

void split_2_hw::thread_key_stream_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        key_stream_ce0 = ap_const_logic_1;
    } else {
        key_stream_ce0 = ap_const_logic_0;
    }
}

void split_2_hw::thread_key_stream_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        key_stream_ce1 = ap_const_logic_1;
    } else {
        key_stream_ce1 = ap_const_logic_0;
    }
}

void split_2_hw::thread_key_stream_d0() {
    key_stream_d0 = state_matrix_q0.read();
}

void split_2_hw::thread_key_stream_d1() {
    key_stream_d1 = state_matrix_q1.read();
}

void split_2_hw::thread_key_stream_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(icmp_ln54_reg_457_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        key_stream_we0 = ap_const_logic_1;
    } else {
        key_stream_we0 = ap_const_logic_0;
    }
}

void split_2_hw::thread_key_stream_we1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(icmp_ln54_reg_457_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        key_stream_we1 = ap_const_logic_1;
    } else {
        key_stream_we1 = ap_const_logic_0;
    }
}

void split_2_hw::thread_or_ln59_fu_284_p2() {
    or_ln59_fu_284_p2 = (icmp_ln55_fu_240_p2.read() | xor_ln56_fu_278_p2.read());
}

void split_2_hw::thread_or_ln60_fu_404_p2() {
    or_ln60_fu_404_p2 = (trunc_ln56_fu_387_p1.read() | ap_const_lv3_1);
}

void split_2_hw::thread_p_shl_cast_fu_373_p3() {
    p_shl_cast_fu_373_p3 = esl_concat<6,3>(add_ln59_fu_363_p2.read(), ap_const_lv3_0);
}

void split_2_hw::thread_select_ln55_fu_335_p3() {
    select_ln55_fu_335_p3 = (!icmp_ln55_fu_240_p2.read()[0].is_01())? sc_lv<6>(): ((icmp_ln55_fu_240_p2.read()[0].to_bool())? ap_const_lv6_1: add_ln55_1_fu_329_p2.read());
}

void split_2_hw::thread_select_ln59_1_fu_254_p3() {
    select_ln59_1_fu_254_p3 = (!icmp_ln55_fu_240_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln55_fu_240_p2.read()[0].to_bool())? ap_const_lv4_6: k_0_reg_207.read());
}

void split_2_hw::thread_select_ln59_2_fu_262_p3() {
    select_ln59_2_fu_262_p3 = (!icmp_ln55_fu_240_p2.read()[0].is_01())? sc_lv<3>(): ((icmp_ln55_fu_240_p2.read()[0].to_bool())? i_fu_234_p2.read(): ap_phi_mux_i_0_phi_fu_157_p4.read());
}

void split_2_hw::thread_select_ln59_3_fu_296_p3() {
    select_ln59_3_fu_296_p3 = (!or_ln59_fu_284_p2.read()[0].is_01())? sc_lv<4>(): ((or_ln59_fu_284_p2.read()[0].to_bool())? select_ln59_1_fu_254_p3.read(): ap_const_lv4_6);
}

void split_2_hw::thread_select_ln59_4_fu_304_p3() {
    select_ln59_4_fu_304_p3 = (!or_ln59_fu_284_p2.read()[0].is_01())? sc_lv<3>(): ((or_ln59_fu_284_p2.read()[0].to_bool())? select_ln59_fu_246_p3.read(): j_fu_290_p2.read());
}

void split_2_hw::thread_select_ln59_fu_246_p3() {
    select_ln59_fu_246_p3 = (!icmp_ln55_fu_240_p2.read()[0].is_01())? sc_lv<3>(): ((icmp_ln55_fu_240_p2.read()[0].to_bool())? ap_const_lv3_0: ap_phi_mux_j_0_phi_fu_179_p4.read());
}

void split_2_hw::thread_sext_ln59_fu_390_p1() {
    sext_ln59_fu_390_p1 = esl_sext<9,4>(select_ln59_3_reg_472.read());
}

void split_2_hw::thread_state_matrix_address0() {
    state_matrix_address0 =  (sc_lv<8>) (zext_ln59_3_fu_399_p1.read());
}

void split_2_hw::thread_state_matrix_address1() {
    state_matrix_address1 =  (sc_lv<8>) (zext_ln60_2_fu_420_p1.read());
}

void split_2_hw::thread_state_matrix_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        state_matrix_ce0 = ap_const_logic_1;
    } else {
        state_matrix_ce0 = ap_const_logic_0;
    }
}

void split_2_hw::thread_state_matrix_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        state_matrix_ce1 = ap_const_logic_1;
    } else {
        state_matrix_ce1 = ap_const_logic_0;
    }
}

void split_2_hw::thread_tmp_1_fu_270_p3() {
    tmp_1_fu_270_p3 = k_0_reg_207.read().range(3, 3);
}

void split_2_hw::thread_tmp_s_fu_349_p3() {
    tmp_s_fu_349_p3 = esl_concat<3,2>(select_ln59_2_reg_466.read(), ap_const_lv2_0);
}

void split_2_hw::thread_trunc_ln56_fu_387_p1() {
    trunc_ln56_fu_387_p1 = select_ln59_3_reg_472.read().range(3-1, 0);
}

void split_2_hw::thread_xor_ln56_fu_278_p2() {
    xor_ln56_fu_278_p2 = (tmp_1_fu_270_p3.read() ^ ap_const_lv1_1);
}

void split_2_hw::thread_zext_ln59_1_fu_360_p1() {
    zext_ln59_1_fu_360_p1 = esl_zext<6,3>(select_ln59_4_reg_478.read());
}

void split_2_hw::thread_zext_ln59_2_fu_369_p1() {
    zext_ln59_2_fu_369_p1 = esl_zext<9,6>(add_ln59_fu_363_p2.read());
}

void split_2_hw::thread_zext_ln59_3_fu_399_p1() {
    zext_ln59_3_fu_399_p1 = esl_zext<64,9>(add_ln59_2_fu_393_p2.read());
}

void split_2_hw::thread_zext_ln59_4_fu_425_p1() {
    zext_ln59_4_fu_425_p1 = esl_zext<64,11>(count1_2_reg_186.read());
}

void split_2_hw::thread_zext_ln59_fu_356_p1() {
    zext_ln59_fu_356_p1 = esl_zext<6,5>(tmp_s_fu_349_p3.read());
}

void split_2_hw::thread_zext_ln60_1_fu_436_p1() {
    zext_ln60_1_fu_436_p1 = esl_zext<64,11>(add_ln60_fu_430_p2.read());
}

void split_2_hw::thread_zext_ln60_2_fu_420_p1() {
    zext_ln60_2_fu_420_p1 = esl_zext<64,9>(add_ln60_1_fu_414_p2.read());
}

void split_2_hw::thread_zext_ln60_fu_410_p1() {
    zext_ln60_fu_410_p1 = esl_zext<9,3>(or_ln60_fu_404_p2.read());
}

void split_2_hw::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

